import React, { useEffect, useState } from 'react';
import { Activity, Ban, CheckCircle2, Clock3, FileText, History, Lock, RefreshCw, ShieldCheck, UserRound, Wallet, X } from 'lucide-react';
import { authHeaders } from '../utils/authHeaders';

type Detail = { user:any; ledger:any[]; withdrawals:any[]; audit:any[] };

function value(v:any) { return v === null || v === undefined || v === '' ? '—' : String(v); }
function money(v:any,currency='USD') { const n=Number(v||0); return `${currency} ${n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8})}`; }
function date(v:any) { if(!v) return '—'; const d=new Date(v); return Number.isNaN(d.getTime()) ? String(v) : d.toLocaleString(); }

export default function AdminUserDetailDrawer({ userId, onClose, showToast }:{userId:string|null;onClose:()=>void;showToast:(message:string,type?:'success'|'error'|'info')=>void}) {
  const [data,setData]=useState<Detail|null>(null); const [loading,setLoading]=useState(false); const [tab,setTab]=useState<'overview'|'ledger'|'withdrawals'|'activity'>('overview'); const [saving,setSaving]=useState<string|null>(null);

  const load=async()=>{if(!userId)return;setLoading(true);try{const r=await fetch(`/api/admin/users/${encodeURIComponent(userId)}`,{headers:await authHeaders()});const d=await r.json();if(!r.ok)throw new Error(d.error||'Unable to load user details');setData({user:d.user,ledger:Array.isArray(d.ledger)?d.ledger:[],withdrawals:Array.isArray(d.withdrawals)?d.withdrawals:[],audit:Array.isArray(d.audit)?d.audit:[]});}catch(e:any){showToast(e?.message||'Unable to load user details','error');setData(null);}finally{setLoading(false);}};
  useEffect(()=>{void load();},[userId]);
  if(!userId)return null;

  const setControl=async(key:string,value:any)=>{if(!data?.user)return;setSaving(key);try{const r=await fetch(`/api/admin/users/${encodeURIComponent(data.user.id)}/controls`,{method:'POST',headers:await authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({[key]:value})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||'Control change failed');setData(prev=>prev?{...prev,user:d.user}:prev);showToast('Account control updated.','success');}catch(e:any){showToast(e?.message||'Control change failed','error');}finally{setSaving(null);}};
  const toggle=async(key:string,current:boolean)=>{await setControl(key,!current);};
  const u=data?.user||{};

  return <div className="fixed inset-0 z-[120] flex justify-end bg-black/60 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="User details">
    <div className="h-full w-full max-w-2xl overflow-y-auto border-l border-white/10 bg-slate-950 text-white shadow-2xl">
      <div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-slate-950/95 px-5 py-4 backdrop-blur"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-full bg-white/10"><UserRound className="h-5 w-5"/></div><div><h2 className="font-bold">{value(u.name)}</h2><p className="text-xs text-slate-400">{value(u.email)} · {value(u.id)}</p></div></div><div className="flex gap-2"><button type="button" onClick={()=>void load()} disabled={loading} className="rounded-lg border border-white/10 p-2" aria-label="Refresh user details"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button><button type="button" onClick={onClose} className="rounded-lg border border-white/10 p-2" aria-label="Close user details"><X className="h-5 w-5"/></button></div></div>
      {loading&&!data?<div className="p-8 text-center text-sm text-slate-400">Loading complete user record…</div>:<div className="space-y-5 p-5">
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><div className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="text-[10px] uppercase text-slate-500">Balance</div><div className="mt-1 font-bold">{money(u.balance)}</div></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="text-[10px] uppercase text-slate-500">Account</div><div className="mt-1 font-semibold">{value(u.status)}</div></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="text-[10px] uppercase text-slate-500">KYC</div><div className="mt-1 font-semibold">{value(u.kyc_status)}</div></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-3"><div className="text-[10px] uppercase text-slate-500">Risk</div><div className="mt-1 font-semibold">{value(u.risk_status)}</div></div></div>
        <section className="rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="mb-3 flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4"/>Account controls</div><div className="grid gap-2 sm:grid-cols-2">{[['allow_login','Login access'],['allow_trading','Trading'],['allow_deposits','Deposits'],['allow_withdrawals','Withdrawals']].map(([key,label])=>{const current=Boolean(u[key]);return <button key={key} type="button" disabled={saving===key} onClick={()=>void toggle(key,current)} className="flex items-center justify-between rounded-lg border border-white/10 px-3 py-3 text-left hover:bg-white/5 disabled:opacity-50"><span>{label}</span><span className={current?'text-emerald-400':'text-rose-400'}>{saving===key?'Saving…':current?'Enabled':'Disabled'}</span></button>})}</div><div className="mt-2 grid gap-2 sm:grid-cols-2"><button type="button" disabled={saving==='status'} onClick={()=>void setControl('status',String(u.status).toLowerCase()==='frozen'?'Active':'Frozen')} className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-3 text-sm hover:bg-white/5"><Lock className="h-4 w-4"/>{String(u.status).toLowerCase()==='frozen'?'Restore account':'Freeze account'}</button><button type="button" disabled={saving==='risk_status'} onClick={()=>void setControl('risk_status',String(u.risk_status).toUpperCase()==='RESTRICTED'?'NORMAL':'RESTRICTED')} className="flex items-center gap-2 rounded-lg border border-white/10 px-3 py-3 text-sm hover:bg-white/5"><Ban className="h-4 w-4"/>{String(u.risk_status).toUpperCase()==='RESTRICTED'?'Clear risk restriction':'Mark risk restricted'}</button></div></section>
        <section className="rounded-xl border border-white/10 bg-white/[.03] p-4"><div className="grid grid-cols-4 gap-1 rounded-lg bg-white/5 p-1">{[['overview','Overview'],['ledger','Ledger'],['withdrawals','Withdrawals'],['activity','Activity']].map(([id,label])=><button key={id} type="button" onClick={()=>setTab(id as any)} className={`rounded-md px-2 py-2 text-xs font-semibold ${tab===id?'bg-white text-slate-950':'text-slate-400'}`}>{label}</button>)}</div>
          {tab==='overview'&&<div className="mt-4 space-y-4"><div><h3 className="mb-2 flex items-center gap-2 text-sm font-semibold"><UserRound className="h-4 w-4"/>Profile</h3><div className="grid gap-2 sm:grid-cols-2">{[['Name',u.name],['Email',u.email],['Phone',u.phone],['Country',u.country],['Provider',u.provider],['User ID',u.id],['Registered',date(u.registered_at)],['Last active',date(u.last_active)],['Updated',date(u.updated_at)],['Verification',u.verification_status],['KYC',u.kyc_status],['Demo balance',money(u.demo_balance)]].map(([k,v])=><div key={k} className="rounded-lg bg-white/5 p-3"><div className="text-[10px] uppercase text-slate-500">{k}</div><div className="mt-1 break-words text-sm">{value(v)}</div></div>)}</div></div><div><h3 className="mb-2 flex items-center gap-2 text-sm font-semibold"><Wallet className="h-4 w-4"/>Funding snapshot</h3><div className="grid gap-2 sm:grid-cols-3"><div className="rounded-lg bg-white/5 p-3"><div className="text-xs text-slate-500">Ledger entries</div><div className="mt-1 text-lg font-bold">{data?.ledger.length||0}</div></div><div className="rounded-lg bg-white/5 p-3"><div className="text-xs text-slate-500">Withdrawals</div><div className="mt-1 text-lg font-bold">{data?.withdrawals.length||0}</div></div><div className="rounded-lg bg-white/5 p-3"><div className="text-xs text-slate-500">Current balance</div><div className="mt-1 text-lg font-bold">{money(u.balance)}</div></div></div></div></div>}
          {tab==='ledger'&&<div className="mt-4 space-y-2">{data?.ledger.length?data.ledger.map((e:any)=><div key={String(e.id)} className="rounded-lg border border-white/10 p-3"><div className="flex items-center justify-between gap-3"><div className="font-semibold">{value(e.entry_type)}</div><div className={Number(e.amount)>=0?'text-emerald-400':'text-rose-400'}>{Number(e.amount)>=0?'+':''}{money(e.amount)}</div></div><div className="mt-1 text-xs text-slate-400">Before {money(e.balance_before)} → After {money(e.balance_after)} · {date(e.created_at)}</div><div className="mt-1 text-xs text-slate-500">{value(e.reason)} · Ref {value(e.reference_id)} · Actor {value(e.actor)}</div></div>):<p className="py-8 text-center text-sm text-slate-500">No ledger entries.</p>}</div>}
          {tab==='withdrawals'&&<div className="mt-4 space-y-2">{data?.withdrawals.length?data.withdrawals.map((w:any)=><div key={w.id} className="rounded-lg border border-white/10 p-3"><div className="flex items-center justify-between"><div className="font-semibold">{money(w.amount,w.currency)}</div><div className="text-xs font-bold">{value(w.status)}</div></div><div className="mt-1 text-xs text-slate-400">{value(w.method)} · {date(w.created_at)}</div><div className="mt-1 text-xs text-slate-500">Review: {value(w.reviewed_by)} · {date(w.reviewed_at)}</div></div>):<p className="py-8 text-center text-sm text-slate-500">No withdrawals.</p>}</div>}
          {tab==='activity'&&<div className="mt-4 space-y-2">{data?.audit.length?data.audit.map((a:any)=><div key={String(a.id)} className="rounded-lg border border-white/10 p-3"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2 font-semibold"><Activity className="h-4 w-4"/>{value(a.action)}</div><div className="text-xs text-slate-500">{date(a.created_at)}</div></div><div className="mt-1 text-xs text-slate-400">Actor: {value(a.actor)}</div><pre className="mt-2 max-h-28 overflow-auto whitespace-pre-wrap break-words text-[10px] text-slate-500">{typeof a.metadata==='string'?a.metadata:JSON.stringify(a.metadata||{},null,2)}</pre></div>):<p className="py-8 text-center text-sm text-slate-500">No recorded activity for this user.</p>}</div>}
        </section>
      </div>}
    </div>
  </div>;
}
