import React, { useEffect, useMemo, useState } from 'react';
import { useSiteCMS } from '../hooks/useSiteCMS';
import { ViewType, DisplayCurrency } from '../types';
import AdminFundingQueue from './AdminFundingQueue';
import AdminPaymentMethods from './AdminPaymentMethods';
import AdminUserDetailDrawer from './AdminUserDetailDrawer';
import { adminAuthHeaders } from '../utils/authHeaders';
import { RefreshCw, CheckCircle2, XCircle, Users, ShieldCheck, Wallet, Search, LogOut, Activity, Plus, Minus, History, UserRound } from 'lucide-react';

interface Props { transactions:any[]; updateTransactionStatus:(id:string,status:string)=>void; setLiveBalance:React.Dispatch<React.SetStateAction<number>>; liveBalance:number; setView:(view:ViewType)=>void; showToast:(msg:string,type:'success'|'error'|'info')=>void; displayCurrency?:DisplayCurrency; setDisplayCurrency?:(curr:DisplayCurrency)=>void; formatCurrency?:(usdAmount:number,targetCurrency?:DisplayCurrency,decimals?:number)=>string; }
interface UserRecord { id:string; name?:string; email:string; status?:string; verificationStatus?:string; kycStatus?:string; balance?:number; registered_at?:string; registeredAt?:string; }
interface KycRecord { id:string; user?:string; userEmail?:string; type?:string; status?:string; submittedAt?:string; documents?:Array<{label:string;url:string;fileName:string}>; rejectionReason?:string; }
interface LedgerEntry { id?:string; amount?:number; balanceAfter?:number; reason?:string; adminEmail?:string; createdAt?:string; referenceId?:string; }

export default function AdminDashboardView({ setView, showToast, transactions, updateTransactionStatus, liveBalance, displayCurrency='USD', formatCurrency=(amt)=>`$${amt.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}` }: Props) {
  const { cmsContent } = useSiteCMS();
  const [adminToken,setAdminToken]=useState<string|null>(()=>typeof window!=='undefined'?window.sessionStorage.getItem('axi_admin_token'):null);
  const [adminPassword,setAdminPassword]=useState(''); const [adminLoginBusy,setAdminLoginBusy]=useState(false); const [adminLoginError,setAdminLoginError]=useState('');
  const [activeTab,setActiveTab]=useState<'overview'|'users'|'kyc'|'funding'|'payments'>('overview');
  const [users,setUsers]=useState<UserRecord[]>([]); const [kyc,setKyc]=useState<KycRecord[]>([]); const [loadingUsers,setLoadingUsers]=useState(false); const [loadingKyc,setLoadingKyc]=useState(false); const [userSearch,setUserSearch]=useState('');
  const [adjustUser,setAdjustUser]=useState<UserRecord|null>(null); const [adjustAmount,setAdjustAmount]=useState(''); const [adjustReason,setAdjustReason]=useState(''); const [adjustDirection,setAdjustDirection]=useState<1|-1>(1); const [adjustBusy,setAdjustBusy]=useState(false);
  const [ledgerUser,setLedgerUser]=useState<UserRecord|null>(null); const [ledger,setLedger]=useState<LedgerEntry[]>([]); const [ledgerLoading,setLedgerLoading]=useState(false);
  const [adminUserDetailId,setAdminUserDetailId]=useState<string|null>(null);

  const submitAdminLogin=async(e:React.FormEvent)=>{e.preventDefault();setAdminLoginBusy(true);setAdminLoginError('');try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:adminPassword})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.token)throw new Error(d.error||'Administrator sign-in failed');window.sessionStorage.setItem('axi_admin_token',d.token);setAdminToken(d.token);setAdminPassword('');}catch(err:any){setAdminLoginError(err?.message||'Administrator sign-in failed')}finally{setAdminLoginBusy(false)}};
  const logout=()=>{window.sessionStorage.removeItem('axi_admin_token');setAdminToken(null);};
  useEffect(()=>{document.title='AXITRADES Admin';},[]);
  const loadUsers=async()=>{setLoadingUsers(true);try{const r=await fetch('/api/users',{headers:await adminAuthHeaders()});const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed to load users');setUsers(Array.isArray(d.users)?d.users:[]);}catch(e:any){showToast(e.message||'Could not load users','error');}finally{setLoadingUsers(false);}};
  const loadKyc=async()=>{setLoadingKyc(true);try{const r=await fetch('/api/kyc/list',{headers:await adminAuthHeaders()});const d=await r.json();if(!r.ok)throw new Error(d.error||'Failed to load KYC');setKyc(Array.isArray(d.submissions)?d.submissions:(Array.isArray(d.documents)?d.documents:[]));}catch(e:any){showToast(e.message||'Could not load KYC submissions','error');}finally{setLoadingKyc(false);}};
  useEffect(()=>{if(!adminToken)return;if(activeTab==='users')void loadUsers();if(activeTab==='kyc'){void loadKyc();const timer=window.setInterval(()=>void loadKyc(),10000);return()=>window.clearInterval(timer);}},[activeTab,adminToken]);
  const openAdjust=(u:UserRecord,direction:1|-1)=>{setAdjustUser(u);setAdjustDirection(direction);setAdjustAmount('');setAdjustReason(direction===1?'Manual balance increase':'Manual balance decrease');};
  const submitAdjustment=async(e:React.FormEvent)=>{e.preventDefault();if(!adjustUser)return;const value=Number(adjustAmount);if(!Number.isFinite(value)||value<=0){showToast('Enter a valid amount greater than zero.','error');return;}if(!adjustReason.trim()){showToast('A reason is required for every balance adjustment.','error');return;}setAdjustBusy(true);try{const r=await fetch(`/api/admin/users/${encodeURIComponent(adjustUser.id)}/balance-adjustment`,{method:'POST',headers:await adminAuthHeaders({'Content-Type':'application/json'}),body:JSON.stringify({amount:adjustDirection*value,reason:adjustReason.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.success)throw new Error(d.error||'Balance adjustment failed');const next=Number(d.result?.balanceAfter ?? (Number(adjustUser.balance||0)+adjustDirection*value));setUsers(prev=>prev.map(u=>u.id===adjustUser.id?{...u,balance:next}:u));showToast(`Balance updated for ${adjustUser.email}. New balance: ${formatCurrency(next,displayCurrency)}`,'success');setAdjustUser(null);}catch(err:any){showToast(err?.message||'Balance adjustment failed','error');}finally{setAdjustBusy(false)}};
  const openLedger=async(u:UserRecord)=>{setLedgerUser(u);setLedgerLoading(true);try{const r=await fetch(`/api/admin/balance-ledger/${encodeURIComponent(u.id)}`,{headers:await adminAuthHeaders()});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Unable to load balance ledger');setLedger(Array.isArray(d.entries)?d.entries:[]);}catch(err:any){showToast(err?.message||'Unable to load balance ledger','error');setLedger([]);}finally{setLedgerLoading(false)}};
  const kycAction=async(id:string,action:'approve'|'reject')=>{let reason='';if(action==='reject'){reason=window.prompt('Enter the reason for rejecting this KYC submission:')||'';if(!reason.trim()){showToast('A rejection reason is required.','error');return;}}try{const r=await fetch(`/api/kyc/${action}`,{method:'POST',headers:await adminAuthHeaders({'Content-Type':'application/json'}),body:JSON.stringify({id,...(reason?{reason}: {})})});const d=await r.json();if(!r.ok)throw new Error(d.error||`KYC ${action} failed`);showToast(`KYC ${action}ed successfully.`,'success');await loadKyc();}catch(e:any){showToast(e.message||`KYC ${action} failed`,'error');}};
  const pendingCount=transactions.filter(tx=>/pending|awaiting/i.test(String(tx?.status||''))).length; const pendingKyc=kyc.filter(k=>/pending|review/i.test(String(k.status||''))).length;
  const filteredUsers=useMemo(()=>{const q=userSearch.trim().toLowerCase();return q?users.filter(u=>`${u.name||''} ${u.email} ${u.id}`.toLowerCase().includes(q)):users;},[users,userSearch]);
  const tabs=[['overview','Overview'],['users','Users'],['kyc','KYC Review'],['funding','Funding'],['payments','Payment Settings']] as const;
  if(!adminToken)return <div className="min-h-screen bg-slate-950 text-white flex items-center justify-center p-6"><form onSubmit={submitAdminLogin} className="w-full max-w-md rounded-2xl border border-white/10 bg-white/[.04] p-6 shadow-2xl"><div className="mb-6"><div className="text-[10px] font-black uppercase tracking-[0.3em] text-red-400">AxiTrades</div><h1 className="mt-2 text-3xl font-black">Administrator Access</h1><p className="mt-2 text-sm text-slate-400">Private production operations access.</p></div><input value={adminPassword} onChange={e=>setAdminPassword(e.target.value)} type="password" autoComplete="current-password" required placeholder="Password" className="w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-sm text-white"/>{adminLoginError&&<p className="mt-3 rounded-lg bg-red-500/10 p-3 text-xs text-red-300">{adminLoginError}</p>}<button disabled={adminLoginBusy} className="mt-5 w-full rounded-xl bg-red-600 py-3.5 text-sm font-black disabled:opacity-60">{adminLoginBusy?'Signing in…':'Enter administrator password'}</button></form></div>;
  void cmsContent;
  return <div className="min-h-screen bg-slate-950 text-white"><header className="border-b border-white/10 px-6 py-5"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">AXITRADES Admin</h1><p className="mt-1 text-sm text-slate-400">Production operations — authenticated administrator access</p></div><div className="flex gap-2"><button type="button" onClick={logout} className="inline-flex items-center gap-2 rounded-lg border border-white/10 px-4 py-2 text-sm"><LogOut className="h-4 w-4"/>Sign out</button><button type="button" onClick={()=>setView('dashboard')} className="rounded-lg border border-white/10 px-4 py-2 text-sm">Back to Dashboard</button></div></div></header>
  <main className="mx-auto max-w-7xl space-y-6 p-6"><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs uppercase text-slate-400">Available Balance</p><p className="mt-2 text-2xl font-semibold">{formatCurrency(liveBalance,displayCurrency)}</p></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs uppercase text-slate-400">Pending Transactions</p><p className="mt-2 text-2xl font-semibold">{pendingCount}</p></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs uppercase text-slate-400">Registered Users</p><p className="mt-2 text-2xl font-semibold">{users.length || '—'}</p></div><div className="rounded-xl border border-white/10 bg-white/[.03] p-5"><p className="text-xs uppercase text-slate-400">KYC Awaiting Review</p><p className="mt-2 text-2xl font-semibold">{pendingKyc}</p></div></section>
  <nav className="flex flex-wrap gap-2 border-b border-white/10 pb-3">{tabs.map(([id,label])=><button key={id} type="button" onClick={()=>setActiveTab(id)} className={`rounded-lg px-4 py-2 text-sm font-medium ${activeTab===id?'bg-white text-slate-950':'bg-white/5 text-slate-300'}`}>{label}</button>)}</nav>
  {activeTab==='overview'&&<section className="rounded-xl border border-white/10 bg-white/[.03] p-6"><h2 className="text-lg font-semibold flex items-center gap-2"><Activity className="h-5 w-5"/>Operations overview</h2><p className="mt-1 text-sm text-slate-400">Use the dedicated queues for persisted production records. Payment credits should only be applied after external payment verification.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><button onClick={()=>setActiveTab('funding')} className="rounded-xl border border-white/10 p-4 text-left hover:bg-white/5"><Wallet className="h-5 w-5"/><div className="mt-2 font-semibold">Review funding</div><div className="text-xs text-slate-500">{pendingCount} pending transaction(s)</div></button><button onClick={()=>{setActiveTab('users');void loadUsers();}} className="rounded-xl border border-white/10 p-4 text-left hover:bg-white/5"><Users className="h-5 w-5"/><div className="mt-2 font-semibold">Manage users</div><div className="text-xs text-slate-500">Balances, adjustments and ledger</div></button><button onClick={()=>{setActiveTab('kyc');void loadKyc();}} className="rounded-xl border border-white/10 p-4 text-left hover:bg-white/5"><ShieldCheck className="h-5 w-5"/><div className="mt-2 font-semibold">Review KYC</div><div className="text-xs text-slate-500">{pendingKyc} awaiting review</div></button></div></section>}
  {activeTab==='users'&&<section className="rounded-xl border border-white/10 bg-white/[.03] p-6"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-lg font-semibold flex items-center gap-2"><Users className="w-5 h-5"/>Registered users</h2><p className="text-sm text-slate-400">Server-side users with auditable balance controls.</p></div><div className="flex gap-2"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-500"/><input value={userSearch} onChange={e=>setUserSearch(e.target.value)} placeholder="Search name, email or ID" className="w-64 rounded-lg border border-white/10 bg-slate-900 py-2 pl-9 pr-3 text-sm"/></div><button onClick={()=>void loadUsers()} disabled={loadingUsers} className="rounded-lg border border-white/10 px-3 py-2 text-sm flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loadingUsers?'animate-spin':''}`}/>Refresh</button></div></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-slate-400"><tr><th className="p-3">User</th><th className="p-3">Status</th><th className="p-3">KYC</th><th className="p-3">Balance</th><th className="p-3">Registered</th><th className="p-3">Actions</th></tr></thead><tbody>{filteredUsers.map(u=><tr key={u.id} className="border-t border-white/10"><td className="p-3"><div className="font-medium">{u.name||'—'}</div><div className="text-xs text-slate-400">{u.email}</div></td><td className="p-3">{u.status||'Pending'}</td><td className="p-3">{u.kycStatus||'NOT_STARTED'}</td><td className="p-3 font-semibold">{formatCurrency(Number(u.balance||0),displayCurrency)}</td><td className="p-3 text-slate-400">{u.registered_at||u.registeredAt||'—'}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>openAdjust(u,1)} className="inline-flex items-center gap-1 rounded-md bg-emerald-500/15 px-2.5 py-2 text-xs font-semibold text-emerald-300"><Plus className="h-3.5 w-3.5"/>Increase</button><button type="button" onClick={()=>openAdjust(u,-1)} className="inline-flex items-center gap-1 rounded-md bg-rose-500/15 px-2.5 py-2 text-xs font-semibold text-rose-300"><Minus className="h-3.5 w-3.5"/>Decrease</button><button type="button" onClick={()=>void openLedger(u)} className="inline-flex items-center gap-1 rounded-md border border-white/10 px-2.5 py-2 text-xs"><History className="h-3.5 w-3.5"/>Ledger</button><button type="button" onClick={()=>setAdminUserDetailId(u.id)} className="inline-flex items-center gap-1 rounded-md border border-white/10 px-2.5 py-2 text-xs"><UserRound className="h-3.5 w-3.5"/>View</button></div></td></tr>)}</tbody></table>{!filteredUsers.length&&!loadingUsers&&<p className="py-8 text-center text-sm text-slate-500">No matching server-side users.</p>}</div></section>}
  {activeTab==='kyc'&&<section className="rounded-xl border border-white/10 bg-white/[.03] p-6"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold flex items-center gap-2"><ShieldCheck className="w-5 h-5"/>Manual KYC review</h2><p className="text-sm text-slate-400">Approve or reject only after reviewing submitted documents.</p></div><button onClick={()=>void loadKyc()} disabled={loadingKyc} className="rounded-lg border border-white/10 px-3 py-2 text-sm flex items-center gap-2"><RefreshCw className={`w-4 h-4 ${loadingKyc?'animate-spin':''}`}/>Refresh</button></div><div className="mt-5 space-y-4">{kyc.map(d=><div key={d.id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold">{d.user||'—'}</div><div className="text-xs text-slate-400">{d.userEmail||'—'} · {d.type||'Identity verification'}</div></div><span className="text-xs font-bold">{d.status||'Under Review'}</span></div>{d.documents?.length?<div className="mt-3 flex flex-wrap gap-2">{d.documents.map((doc,i)=><a key={i} href={doc.url} target="_blank" rel="noreferrer" className="rounded-md border border-white/10 px-3 py-2 text-xs text-slate-200 hover:bg-white/5">View {doc.label||doc.fileName}</a>)}</div>:null}<div className="mt-4 flex gap-2"><button type="button" onClick={()=>void kycAction(d.id,'approve')} className="rounded-md bg-emerald-500/20 px-3 py-2 text-xs text-emerald-300 flex items-center gap-1"><CheckCircle2 className="w-4 h-4"/>Approve</button><button type="button" onClick={()=>void kycAction(d.id,'reject')} className="rounded-md bg-rose-500/20 px-3 py-2 text-xs text-rose-300 flex items-center gap-1"><XCircle className="w-4 h-4"/>Reject</button></div></div>)}{!kyc.length&&!loadingKyc&&<p className="py-8 text-center text-sm text-slate-500">No KYC submissions available for review.</p>}</div></section>}
  {activeTab==='funding'&&<AdminFundingQueue showToast={showToast}/>} {activeTab==='payments'&&<AdminPaymentMethods showToast={showToast}/>}<AdminUserDetailDrawer userId={adminUserDetailId} onClose={()=>setAdminUserDetailId(null)} showToast={showToast}/></main>
  {adjustUser&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form onSubmit={submitAdjustment} className="w-full max-w-md rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h3 className="text-lg font-bold">{adjustDirection===1?'Increase':'Decrease'} user balance</h3><p className="mt-1 text-xs text-slate-400">{adjustUser.name||adjustUser.email} · Current {formatCurrency(Number(adjustUser.balance||0),displayCurrency)}</p></div><button type="button" onClick={()=>setAdjustUser(null)} className="text-slate-400">×</button></div><label className="mt-5 block text-xs font-semibold text-slate-300">Amount</label><input type="number" min="0.01" step="0.01" required value={adjustAmount} onChange={e=>setAdjustAmount(e.target.value)} placeholder="0.00" className="mt-2 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-3"/><label className="mt-4 block text-xs font-semibold text-slate-300">Reason / audit note</label><textarea required value={adjustReason} onChange={e=>setAdjustReason(e.target.value)} rows={3} placeholder="Why is this balance being adjusted?" className="mt-2 w-full rounded-lg border border-white/10 bg-slate-950 px-3 py-3 text-sm"/><div className="mt-5 flex gap-2"><button type="button" onClick={()=>setAdjustUser(null)} className="flex-1 rounded-lg border border-white/10 py-3 text-sm">Cancel</button><button disabled={adjustBusy} className={`flex-1 rounded-lg py-3 text-sm font-bold ${adjustDirection===-1?'bg-rose-600':'bg-emerald-600'}`}>{adjustBusy?'Saving…':adjustDirection===-1?'Confirm decrease':'Confirm increase'}</button></div></form></div>}
  {ledgerUser&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-2xl rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h3 className="text-lg font-bold">Balance ledger</h3><p className="text-xs text-slate-400">{ledgerUser.email}</p></div><button onClick={()=>setLedgerUser(null)} className="text-slate-400">×</button></div><div className="mt-5 max-h-[60vh] overflow-auto">{ledgerLoading?<p className="py-8 text-center text-slate-500">Loading ledger…</p>:ledger.length?<div className="space-y-2">{ledger.map((entry,i)=><div key={String(entry.id||i)} className="rounded-lg border border-white/10 p-3"><div className="flex justify-between gap-3"><span className={Number(entry.amount||0)>=0?'text-emerald-300':'text-rose-300'}>{Number(entry.amount||0)>=0?'+':''}{Number(entry.amount||0).toFixed(2)}</span><span className="font-semibold">Balance {formatCurrency(Number(entry.balanceAfter||0),displayCurrency)}</span></div><p className="mt-1 text-xs text-slate-400">{entry.reason||'Balance adjustment'} · {entry.adminEmail||'Administrator'} · {entry.createdAt?new Date(entry.createdAt).toLocaleString():'—'}{entry.referenceId?` · ${entry.referenceId}`:''}</p></div>)}</div>:<p className="py-8 text-center text-slate-500">No ledger entries found.</p>}</div></div></div>}
  </div>;
}
