import React, { useEffect, useState } from 'react';
import { Banknote, Bitcoin, Plus, RefreshCw, Save, Smartphone, Trash2, WalletCards } from 'lucide-react';
import { authHeaders } from '../utils/authHeaders';

type BankTransfer={enabled:boolean;bankName:string;accountName:string;accountNumber:string;routingNumber:string;swiftBic:string;currency:string;instructions:string};
type InstantTransfer={enabled:boolean;providerName:string;accountName:string;accountNumber:string;instructions:string};
type CryptoWallet={id:string;enabled:boolean;asset:string;network:string;address:string;memo:string;label:string;instructions:string};
type EWallet={enabled:boolean;account:string;accountName:string;instructions:string};
type PaymentMethods={bankTransfer:BankTransfer;instantTransfer:InstantTransfer;crypto:CryptoWallet[];paypal:EWallet;skrill:EWallet;neteller:EWallet};
const emptyBank={enabled:false,bankName:'',accountName:'',accountNumber:'',routingNumber:'',swiftBic:'',currency:'',instructions:''};
const emptyInstant={enabled:false,providerName:'',accountName:'',accountNumber:'',instructions:''};
const emptyEWallet={enabled:false,account:'',accountName:'',instructions:''};
const newWallet=():CryptoWallet=>({id:`new-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,enabled:true,asset:'',network:'',address:'',memo:'',label:'',instructions:''});
export default function AdminPaymentMethods({showToast}:{showToast:(message:string,type?:'success'|'error'|'info')=>void}){
 const [methods,setMethods]=useState<PaymentMethods>({bankTransfer:emptyBank,instantTransfer:emptyInstant,crypto:[],paypal:emptyEWallet,skrill:emptyEWallet,neteller:emptyEWallet});
 const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);
 const load=async()=>{setLoading(true);try{const headers=await authHeaders();const res=await fetch('/api/admin/payment-methods',{headers});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||'Unable to load payment settings');const raw=Array.isArray(data.methods?.crypto)?data.methods.crypto:(data.methods?.crypto?[data.methods.crypto]:[]);const ew=(key:string):EWallet=>({...emptyEWallet,...(data.methods?.[key]||{})});setMethods({bankTransfer:{...emptyBank,...(data.methods?.bankTransfer||{})},instantTransfer:{...emptyInstant,...(data.methods?.instantTransfer||{})},crypto:raw.map((w:any,i:number)=>({id:String(w.id||`crypto-${i}`),enabled:Boolean(w.enabled),asset:String(w.asset||''),network:String(w.network||''),address:String(w.address||w.walletAddress||''),memo:String(w.memo||''),label:String(w.label||''),instructions:String(w.instructions||'')})),paypal:ew('paypal'),skrill:ew('skrill'),neteller:ew('neteller')});}catch(e:any){showToast(e?.message||'Unable to load payment settings.','error')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const updateGroup=(group:'bankTransfer'|'instantTransfer',field:string,value:string|boolean)=>setMethods(p=>({...p,[group]:{...p[group],[field]:value}} as PaymentMethods));
 const updateEWallet=(group:'paypal'|'skrill'|'neteller',field:keyof EWallet,value:string|boolean)=>setMethods(p=>({...p,[group]:{...p[group],[field]:value}}));
 const updateWallet=(id:string,field:keyof CryptoWallet,value:string|boolean)=>setMethods(p=>({...p,crypto:p.crypto.map(w=>w.id===id?{...w,[field]:value}:w)}));
 const addWallet=()=>setMethods(p=>({...p,crypto:[...p.crypto,newWallet()]}));
 const removeWallet=(id:string)=>setMethods(p=>({...p,crypto:p.crypto.filter(w=>w.id!==id)}));
 const save=async()=>{const invalid=methods.crypto.find(w=>w.enabled&&(!w.asset.trim()||!w.network.trim()||!w.address.trim()));if(invalid)return showToast('Every enabled crypto wallet needs an asset, network, and wallet address.','error');const invalidE=(['paypal','skrill','neteller'] as const).find(k=>methods[k].enabled&&!methods[k].account.trim());if(invalidE)return showToast(`Enter the ${invalidE} receiving account before enabling it.`,'error');setSaving(true);try{const headers=await authHeaders({'Content-Type':'application/json'});const res=await fetch('/api/admin/payment-methods',{method:'POST',headers,body:JSON.stringify(methods)});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error||'Unable to save payment settings');showToast('Payment details saved successfully.','success');await load()}catch(e:any){showToast(e?.message||'Payment settings could not be saved.','error')}finally{setSaving(false)}};
 const input='w-full rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm outline-none focus:border-orange-400 dark:border-slate-700 dark:bg-slate-950 dark:text-white';
 const Field=({label,value,onChange,placeholder=''}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string})=><label className="block space-y-1"><span className="text-xs font-semibold text-slate-600 dark:text-slate-300">{label}</span><input className={input} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>;
 const EWalletCard=({id,title,help}:{id:'paypal'|'skrill'|'neteller';title:string;help:string})=><section className="rounded-2xl border border-slate-200 p-5 dark:border-slate-700"><div className="mb-4 flex items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 font-bold"><WalletCards className="h-5 w-5"/>{title}</h3><p className="mt-1 text-xs text-slate-500">{help}</p></div><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={methods[id].enabled} onChange={e=>updateEWallet(id,'enabled',e.target.checked)}/> Enabled</label></div><div className="grid gap-4 md:grid-cols-2"><Field label={`${title} account / receiving email`} value={methods[id].account} onChange={v=>updateEWallet(id,'account',v.trim())} placeholder={`Enter the ${title} receiving account`}/><Field label="Account name (optional)" value={methods[id].accountName} onChange={v=>updateEWallet(id,'accountName',v)} placeholder="Business or account holder name"/></div><label className="mt-4 block space-y-1"><span className="text-xs font-semibold text-slate-600 dark:text-slate-300">Customer deposit instructions</span><textarea className={input} rows={3} value={methods[id].instructions} onChange={e=>updateEWallet(id,'instructions',e.target.value)} placeholder="Tell customers exactly how to send the payment and what reference to include."/></label></section>;
 if(loading)return <div className="rounded-2xl border border-slate-200 p-6 text-sm text-slate-500">Loading payment settings…</div>;
 return <div className="space-y-6"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold text-slate-900 dark:text-white">Payment Method Control</h2><p className="mt-1 text-xs text-slate-500">Configure the real deposit instructions customers see. Enable a method only after its receiving details are entered.</p></div><button type="button" onClick={load} className="rounded-lg border border-slate-200 p-2 dark:border-slate-700" aria-label="Refresh payment methods"><RefreshCw className="h-4 w-4"/></button></div>
 <section className="rounded-2xl border border-slate-200 p-5 dark:border-slate-700"><div className="mb-4 flex items-center justify-between"><h3 className="flex items-center gap-2 font-bold"><Banknote className="h-5 w-5"/> Bank Transfer</h3><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={methods.bankTransfer.enabled} onChange={e=>updateGroup('bankTransfer','enabled',e.target.checked)}/> Enabled</label></div><div className="grid gap-4 md:grid-cols-2"><Field label="Bank name" value={methods.bankTransfer.bankName} onChange={v=>updateGroup('bankTransfer','bankName',v)}/><Field label="Account name" value={methods.bankTransfer.accountName} onChange={v=>updateGroup('bankTransfer','accountName',v)}/><Field label="Account number" value={methods.bankTransfer.accountNumber} onChange={v=>updateGroup('bankTransfer','accountNumber',v)}/><Field label="Routing / sort code" value={methods.bankTransfer.routingNumber} onChange={v=>updateGroup('bankTransfer','routingNumber',v)}/><Field label="SWIFT / BIC" value={methods.bankTransfer.swiftBic} onChange={v=>updateGroup('bankTransfer','swiftBic',v)}/><Field label="Currency" value={methods.bankTransfer.currency} onChange={v=>updateGroup('bankTransfer','currency',v)}/></div><label className="mt-4 block space-y-1"><span className="text-xs font-semibold text-slate-600 dark:text-slate-300">Customer instructions</span><textarea className={input} rows={3} value={methods.bankTransfer.instructions} onChange={e=>updateGroup('bankTransfer','instructions',e.target.value)}/></label></section>
 <section className="rounded-2xl border border-slate-200 p-5 dark:border-slate-700"><div className="mb-4 flex items-center justify-between"><h3 className="flex items-center gap-2 font-bold"><Smartphone className="h-5 w-5"/> Instant Transfer</h3><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={methods.instantTransfer.enabled} onChange={e=>updateGroup('instantTransfer','enabled',e.target.checked)}/> Enabled</label></div><div className="grid gap-4 md:grid-cols-2"><Field label="Provider / bank" value={methods.instantTransfer.providerName} onChange={v=>updateGroup('instantTransfer','providerName',v)}/><Field label="Account name" value={methods.instantTransfer.accountName} onChange={v=>updateGroup('instantTransfer','accountName',v)}/><Field label="Account / wallet number" value={methods.instantTransfer.accountNumber} onChange={v=>updateGroup('instantTransfer','accountNumber',v)}/></div><label className="mt-4 block space-y-1"><span className="text-xs font-semibold text-slate-600 dark:text-slate-300">Customer instructions</span><textarea className={input} rows={3} value={methods.instantTransfer.instructions} onChange={e=>updateGroup('instantTransfer','instructions',e.target.value)}/></label></section>
 <EWalletCard id="paypal" title="PayPal" help="Customers will see this as a manual PayPal deposit option."/><EWalletCard id="skrill" title="Skrill" help="Customers will see this as a manual Skrill deposit option."/><EWalletCard id="neteller" title="Neteller" help="Customers will see this as a manual Neteller deposit option."/>
 <section className="rounded-2xl border border-slate-200 p-5 dark:border-slate-700"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h3 className="flex items-center gap-2 font-bold"><Bitcoin className="h-5 w-5"/> Crypto Wallets</h3><p className="mt-1 text-xs text-slate-500">Add as many assets and networks as needed. USDT/USDC can be configured separately per network.</p></div><button type="button" onClick={addWallet} className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4"/> Add Payment Method</button></div>{methods.crypto.length===0?<div className="rounded-xl border border-dashed border-slate-300 p-8 text-center text-sm text-slate-500">No crypto wallets configured yet. Click <strong>Add Payment Method</strong> to add the first wallet.</div>:<div className="space-y-4">{methods.crypto.map((w,i)=><div key={w.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-slate-100 text-xs font-bold dark:bg-slate-800">{i+1}</span><span className="text-sm font-bold">Crypto payment method</span></div><div className="flex items-center gap-3"><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={w.enabled} onChange={e=>updateWallet(w.id,'enabled',e.target.checked)}/> Active</label><button type="button" onClick={()=>removeWallet(w.id)} className="rounded-lg border border-red-200 p-2 text-red-600" aria-label={`Remove crypto wallet ${i+1}`}><Trash2 className="h-4 w-4"/></button></div></div><div className="grid gap-4 md:grid-cols-2"><Field label="Asset" value={w.asset} onChange={v=>updateWallet(w.id,'asset',v.toUpperCase())} placeholder="BTC, ETH, USDT, USDC"/><Field label="Network" value={w.network} onChange={v=>updateWallet(w.id,'network',v)} placeholder="Bitcoin, Ethereum, TRON, BSC, Solana, Base"/><div className="md:col-span-2"><Field label="Wallet address" value={w.address} onChange={v=>updateWallet(w.id,'address',v.trim())} placeholder="Enter receiving wallet address"/></div><Field label="Label (optional)" value={w.label} onChange={v=>updateWallet(w.id,'label',v)}/><Field label="Memo / tag (optional)" value={w.memo} onChange={v=>updateWallet(w.id,'memo',v)}/></div><label className="mt-4 block space-y-1"><span className="text-xs font-semibold text-slate-600 dark:text-slate-300">Customer instructions (optional)</span><textarea className={input} rows={2} value={w.instructions} onChange={e=>updateWallet(w.id,'instructions',e.target.value)}/></label></div>)}</div>}</section>
 <div className="flex justify-end"><button type="button" disabled={saving} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving?'Saving…':'Save Payment Details'}</button></div><p className="text-xs text-slate-500">Card payments remain handled by Stripe. PayPal, Skrill, Neteller, bank, instant transfer, and crypto options are manual deposit instructions unless a separate provider integration is configured.</p></div>;
}
