import React, { useEffect, useState } from 'react';
import { CheckCircle2, Clock3, CreditCard, RefreshCw, XCircle } from 'lucide-react';
import { authHeaders } from '../utils/authHeaders';

interface PendingDeposit { id:string; userEmail:string; amount:number; currency?:string; method:string; status:string; stripeRef?:string; receivedAt:string; creditedByAdmin?:boolean; user?:{id?:string;email?:string;name?:string;balance?:number}; }

export default function AdminFundingQueue({ showToast }:{showToast:(message:string,type?:'success'|'error'|'info')=>void}) {
  const [items,setItems]=useState<PendingDeposit[]>([]); const [loading,setLoading]=useState(false); const [busy,setBusy]=useState<string|null>(null);
  const load=async()=>{setLoading(true);try{const res=await fetch('/api/admin/funding/pending',{headers:await authHeaders()});const data=await res.json();if(!res.ok)throw new Error(data.error||'Unable to load funding queue');if(Array.isArray(data.deposits))setItems(data.deposits);}catch(error:any){showToast(error?.message||'Funding queue load failed.','error');}finally{setLoading(false);}};
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),8000);return()=>window.clearInterval(timer);},[]);
  const approve=async(deposit:PendingDeposit)=>{if(!deposit.user?.id){showToast('This funding record has no verified user account. Investigate it before approval.','error');return;}setBusy(deposit.id);try{const res=await fetch(`/api/admin/funding/${encodeURIComponent(deposit.id)}/credit`,{method:'POST',headers:await authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({userId:deposit.user.id})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.success)throw new Error(data.error||'Funding approval failed.');showToast(`$${Number(deposit.amount).toLocaleString(undefined,{minimumFractionDigits:2})} credited to ${deposit.userEmail}.`,'success');await load();}catch(error:any){showToast(error?.message||'Funding approval failed.','error');}finally{setBusy(null);}};
  const reject=async(deposit:PendingDeposit)=>{setBusy(deposit.id);try{const res=await fetch(`/api/admin/funding/${encodeURIComponent(deposit.id)}/reject`,{method:'POST',headers:await authHeaders({'Content-Type':'application/json'}),body:JSON.stringify({reason:'Rejected during administrator funding review'})});const data=await res.json().catch(()=>({}));if(!res.ok||!data.success)throw new Error(data.error||'Could not reject payment.');showToast('Funding request rejected. No balance was credited.','info');await load();}catch(error:any){showToast(error?.message||'Rejection failed.','error');}finally{setBusy(null);}};
  return <section className="mb-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="mb-4 flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold text-slate-900 dark:text-white"><CreditCard className="h-5 w-5"/> Funding Review</h2><p className="mt-1 text-xs text-slate-500">Pending deposits are reviewed server-side. Approval atomically updates the funding record, balance ledger, user balance, and audit trail.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="rounded-lg border border-slate-200 p-2 text-slate-600 hover:bg-slate-50 disabled:opacity-50 dark:border-slate-700 dark:text-slate-300 dark:hover:bg-slate-800" aria-label="Refresh funding queue"><RefreshCw className={`h-4 w-4 ${loading?'animate-spin':''}`}/></button></div>{items.length===0?<div className="rounded-xl border border-dashed border-slate-200 p-6 text-center text-sm text-slate-500 dark:border-slate-700">No payments are awaiting manual credit.</div>:<div className="space-y-3">{items.map(deposit=><div key={deposit.id} className="rounded-xl border border-slate-200 p-4 dark:border-slate-700"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex items-center gap-2 text-sm font-semibold text-slate-900 dark:text-white"><Clock3 className="h-4 w-4"/> {Number(deposit.amount).toLocaleString(undefined,{minimumFractionDigits:2})} {deposit.currency||'USD'}</div><div className="mt-1 text-sm text-slate-600 dark:text-slate-300">{deposit.user?.name||deposit.userEmail}</div><div className="mt-1 text-xs text-slate-500">{deposit.method} · {deposit.stripeRef||deposit.id} · {new Date(deposit.receivedAt).toLocaleString()}</div><div className="mt-1 text-xs font-medium text-amber-600">{deposit.status}</div></div><div className="flex gap-2"><button type="button" disabled={busy===deposit.id} onClick={()=>void reject(deposit)} className="inline-flex items-center gap-1 rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700 hover:bg-red-50 disabled:opacity-50"><XCircle className="h-4 w-4"/> Reject</button><button type="button" disabled={busy===deposit.id} onClick={()=>void approve(deposit)} className="inline-flex items-center gap-1 rounded-lg bg-slate-900 px-3 py-2 text-xs font-semibold text-white hover:bg-slate-800 disabled:opacity-50"><CheckCircle2 className="h-4 w-4"/> Approve & Credit</button></div></div></div>)}</div>}</section>;
}