import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Search, Mail, BookOpen, Clock, Calendar, ArrowRight, Rss, ArrowUpRight } from 'lucide-react';

interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  category: 'Forex' | 'Cryptocurrencies' | 'Commodities' | 'Stock Market' | 'Trading Psychology' | 'Weekly Forecast';
  author: string;
  date: string;
  readTime: string;
  image: string;
  featured?: boolean;
}

const BLOG_POSTS: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'ECB Rate Cut Whispers: How EURUSD is Reacting to Inflation Dips',
    excerpt: 'The European Central Bank prepares for systemic interest rate adjustments as Eurozone inflation cools faster than forecast. We dissect technical key support lines for EUR/USD and the impact on currency majors.',
    category: 'Forex',
    author: 'Daniel Cross (Chief Market Analyst)',
    date: '2026-07-12',
    readTime: '6 min read',
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&q=80&w=600',
    featured: true
  },
  {
    id: 'blog-2',
    title: 'Gold Breaks Records: Will Geopolitical Uncertainties Propel XAUUSD Past $2,400?',
    excerpt: 'Safe-haven assets undergo institutional surges as hedge funds seek shelter from macro geopolitical risks. Technical oscillators suggest key breakout patterns are forming on the Gold daily chart.',
    category: 'Commodities',
    author: 'Elena Rostova (Commodity Lead Analyst)',
    date: '2026-07-10',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1610374792793-f016b77ca51a?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'blog-3',
    title: 'The Bitcoin Halving Cycle: Historical Retracement Paths vs. Spot ETF Liquidity',
    excerpt: 'As Bitcoin navigates post-halving dynamics, we compare traditional cyclic corrections with the persistent demand flow generated by newly authorized US Spot ETFs. Here are the support zones to monitor.',
    category: 'Cryptocurrencies',
    author: 'Marcus Vance (Senior Digital Assets strategist)',
    date: '2026-07-08',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1518546305927-5a555bb7020d?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'blog-4',
    title: 'Navigating S&P 500 Valuations: Tech Giant Earnings & Treasury Yield Shocks',
    excerpt: 'High-beta technology shares trade near premium multiples. We explore whether corporate earnings beats will offset headwinds from resilient US bond yields on the S&P 500 Index CFD index.',
    category: 'Stock Market',
    author: 'Sarah Jenkins (Equity Research Director)',
    date: '2026-07-05',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'blog-5',
    title: 'Discipline in Drawdown: How Top Axi Select Traders Handle Psychological Recovery',
    excerpt: 'Experiencing losses is an inevitable dimension of trading. We interview elite Axi Select funded traders to understand their mental checklist during equity drawdowns and how they protect their Edge Scores.',
    category: 'Trading Psychology',
    author: 'Dr. Arthur Cole (Trader Performance Coach)',
    date: '2026-07-02',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=600'
  },
  {
    id: 'blog-6',
    title: 'Weekly Forecast: Dollar Index Resistance & Key CPI Releases to Watch',
    excerpt: 'Ahead of a high-impact macroeconomic calendar week, we map crucial resistance vectors for the US Dollar Index (DXY) and key levels to trade around incoming Consumer Price Index data.',
    category: 'Weekly Forecast',
    author: 'Daniel Cross (Chief Market Analyst)',
    date: '2026-06-29',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=600'
  }
];

interface BlogViewProps {
  showToast: (msg: string, type: 'success' | 'error' | 'info') => void;
}

export default function BlogView({ showToast }: BlogViewProps) {
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [emailInput, setEmailInput] = useState('');

  const categories = ['All', 'Forex', 'Cryptocurrencies', 'Commodities', 'Stock Market', 'Trading Psychology', 'Weekly Forecast'];

  const handleSubscribe = (e: React.FormEvent) => {
    e.preventDefault();
    if (!emailInput || !emailInput.includes('@')) {
      showToast('Please enter a valid email address.', 'error');
      return;
    }
    showToast('Success! You have subscribed to Axi Daily Market Briefings.', 'success');
    setEmailInput('');
  };

  const filteredPosts = BLOG_POSTS.filter(post => {
    const matchesSearch = post.title.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          post.excerpt.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = selectedCategory === 'All' || post.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const featuredPost = BLOG_POSTS.find(post => post.featured);
  const regularPosts = filteredPosts.filter(post => !post.featured || selectedCategory !== 'All');

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 flex flex-col gap-12 bg-brand-light">
      
      {/* Blog Intro Header */}
      <div className="text-center max-w-3xl mx-auto flex flex-col items-center gap-3">
        <span className="text-brand-red text-xs font-black tracking-widest uppercase bg-brand-red/5 border border-brand-red/10 px-3.5 py-1.5 rounded-full flex items-center gap-2">
          <Rss className="w-3.5 h-3.5 text-brand-yellow fill-brand-yellow/10" /> MARKET RADAR ENGINE
        </span>
        <h1 className="text-3xl md:text-5xl font-black text-brand-dark tracking-tight uppercase">
          Axi Live Intelligence Blog
        </h1>
        <p className="text-slate-500 text-xs sm:text-sm font-semibold">
          Daily technical blueprints, institutional reports, digital asset research, and professional psychology guides compiled by Axi’s global intelligence desk.
        </p>
      </div>

      {/* Interactive Controls Panel */}
      <div className="bg-white border border-slate-200 rounded-2xl p-5 shadow-sm flex flex-col md:flex-row items-center justify-between gap-4">
        
        {/* Search Bar */}
        <div className="relative w-full md:max-w-md">
          <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 w-4 h-4" />
          <input
            type="text"
            placeholder="Search articles, technical terms..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full bg-slate-50 border border-slate-200 focus:border-brand-red focus:bg-white rounded-xl pl-10 pr-4 py-2.5 text-xs text-slate-800 font-semibold focus:outline-none transition shadow-inner"
          />
        </div>

        {/* Categories Scroller */}
        <div className="flex items-center gap-1.5 overflow-x-auto w-full md:w-auto pb-2 md:pb-0 scrollbar-none">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-3 py-2 rounded-lg text-[10px] font-black uppercase tracking-wider border whitespace-nowrap transition duration-150 cursor-pointer ${
                selectedCategory === cat 
                  ? 'bg-brand-red text-white border-brand-red shadow-sm' 
                  : 'bg-slate-50 hover:bg-slate-100 border-slate-200 text-slate-500'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Main Blog Feed display */}
      <div className="flex flex-col gap-10">
        
        {/* Featured Post (Only visible when Category Filter is "All" or match featured post, and no active narrow search) */}
        {selectedCategory === 'All' && searchTerm === '' && featuredPost && (
          <div className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition-all duration-300 grid grid-cols-1 lg:grid-cols-12 items-stretch">
            <div className="lg:col-span-7 h-64 lg:h-auto min-h-[280px] relative">
              <img 
                src={featuredPost.image} 
                alt={featuredPost.title}
                referrerPolicy="no-referrer"
                className="absolute inset-0 w-full h-full object-cover"
              />
              <span className="absolute top-4 left-4 bg-brand-red text-white text-[10px] font-black uppercase px-3 py-1.5 rounded-md shadow-sm tracking-widest">
                Featured Analysis
              </span>
            </div>

            <div className="lg:col-span-5 p-6 md:p-8 flex flex-col justify-between gap-6">
              <div className="flex flex-col gap-3">
                <span className="text-[10px] font-black uppercase text-brand-red tracking-wider">
                  {featuredPost.category}
                </span>
                <h2 className="text-xl md:text-2xl font-black text-brand-dark tracking-tight leading-tight uppercase hover:text-brand-red cursor-pointer transition">
                  {featuredPost.title}
                </h2>
                <p className="text-slate-500 text-xs font-semibold leading-relaxed mt-1">
                  {featuredPost.excerpt}
                </p>
              </div>

              <div className="flex items-center justify-between border-t border-slate-100 pt-4 text-xs font-bold text-slate-500">
                <div className="flex flex-col">
                  <span className="text-slate-700 font-extrabold">{featuredPost.author}</span>
                  <span className="text-[10px] text-slate-400 font-mono mt-0.5">{featuredPost.date} • {featuredPost.readTime}</span>
                </div>
                <button className="text-brand-red flex items-center gap-1 font-black uppercase tracking-wider hover:translate-x-1 transition duration-150 text-[10px]">
                  Read Blueprint <ArrowRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Regular Posts Grid */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          {regularPosts.map((post) => (
            <motion.div
              layout
              key={post.id}
              className="bg-white border border-slate-200 rounded-2xl overflow-hidden shadow-sm hover:shadow-md transition duration-200 flex flex-col h-full justify-between"
            >
              <div>
                <div className="h-44 relative overflow-hidden">
                  <img 
                    src={post.image} 
                    alt={post.title}
                    referrerPolicy="no-referrer"
                    className="absolute inset-0 w-full h-full object-cover hover:scale-105 transition duration-300"
                  />
                  <span className="absolute top-3 right-3 bg-brand-dark/85 backdrop-blur-sm text-white text-[9px] font-black uppercase px-2.5 py-1 rounded">
                    {post.category}
                  </span>
                </div>

                <div className="p-5 flex flex-col gap-2.5">
                  <span className="text-[9px] font-mono text-slate-400 font-bold flex items-center gap-1.5">
                    <Calendar className="w-3 h-3 text-brand-red" /> {post.date} • <Clock className="w-3 h-3 text-brand-red" /> {post.readTime}
                  </span>
                  <h3 className="text-sm font-black text-brand-dark leading-snug line-clamp-2 hover:text-brand-red cursor-pointer transition uppercase">
                    {post.title}
                  </h3>
                  <p className="text-slate-500 text-[11px] font-semibold leading-relaxed line-clamp-3">
                    {post.excerpt}
                  </p>
                </div>
              </div>

              <div className="p-5 border-t border-slate-100 flex items-center justify-between text-xs font-bold text-slate-400 mt-auto">
                <span className="text-[10px] text-slate-650 font-black">{post.author.split(' (')[0]}</span>
                <button className="text-brand-red hover:text-brand-red-hover flex items-center gap-1 font-black uppercase tracking-wider text-[10px] cursor-pointer">
                  View <ArrowUpRight className="w-3.5 h-3.5" />
                </button>
              </div>
            </motion.div>
          ))}

          {filteredPosts.length === 0 && (
            <div className="col-span-full py-16 text-center flex flex-col items-center gap-2">
              <BookOpen className="w-10 h-10 text-slate-300" />
              <span className="text-slate-700 font-black text-sm uppercase">No Intelligence Blueprints Found</span>
              <p className="text-slate-400 text-xs font-semibold">Try modifying your search or filter requirements to check broader topics.</p>
            </div>
          )}
        </div>
      </div>

      {/* Newsletter Subscription Card */}
      <div className="bg-slate-950 text-white rounded-2xl p-6 md:p-10 border border-slate-900 shadow-xl relative overflow-hidden flex flex-col md:flex-row items-center justify-between gap-8">
        <div className="absolute top-0 right-0 w-48 h-48 bg-brand-red/10 rounded-full blur-3xl -z-10"></div>
        
        <div className="flex-1 flex flex-col gap-2">
          <span className="text-[10px] font-black uppercase text-brand-yellow tracking-widest flex items-center gap-1.5">
            <Mail className="w-3.5 h-3.5 text-brand-red fill-brand-yellow" /> Axi Daily Briefings
          </span>
          <h3 className="text-xl md:text-2xl font-black text-white uppercase tracking-tight">
            Institutional intelligence in your inbox
          </h3>
          <p className="text-xs text-slate-400 font-semibold leading-relaxed max-w-lg mt-0.5">
            Subscribe to our weekly research briefs. We deliver precise mathematical spreads, technical charts, ECB/FED decisions, and trading psychology keys directly to you.
          </p>
        </div>

        <form onSubmit={handleSubscribe} className="w-full md:max-w-md shrink-0 flex flex-col gap-2.5 font-semibold text-xs">
          <div className="flex gap-2">
            <input
              type="email"
              placeholder="e.g. trader@example.com"
              value={emailInput}
              onChange={(e) => setEmailInput(e.target.value)}
              className="bg-white/5 border border-white/10 focus:border-brand-yellow focus:bg-white/10 rounded-xl px-4 py-3 text-sm text-white focus:outline-none flex-grow font-mono"
            />
            <button
              type="submit"
              className="bg-brand-yellow hover:bg-brand-yellow-hover text-brand-dark px-5 py-3 font-black uppercase rounded-xl shadow-md cursor-pointer shrink-0"
            >
              Brief Me
            </button>
          </div>
          <p className="text-[9px] text-slate-500 leading-normal">
            By registering, you agree to receive Axi financial communications. You are free to withdraw or opt-out securely at any point.
          </p>
        </form>
      </div>

    </div>
  );
}
