import React, { useState } from 'react';
import { 
  Calculator, 
  BookOpen, 
  CheckCircle2, 
  HelpCircle, 
  Zap, 
  RefreshCcw, 
  Sparkles, 
  Check, 
  X,
  ChevronRight,
  Calendar,
  Bell,
  Filter,
  Clock,
  Globe,
  Info,
  ArrowLeftRight,
  Copy,
  DollarSign,
  TrendingUp,
  Users,
  UserCheck,
  BarChart3,
  Award,
  ShieldAlert,
  PieChart,
  Activity,
  Play,
  Sliders
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { ACADEMY_COURSES, DEFAULT_MARKET_QUOTES } from '../data';
import { MarketQuote } from '../types';

import PositionSizeCalculator from './PositionSizeCalculator';

const FINANCIAL_GLOSSARY: Record<string, string> = {
  'Margin Required': 'The minimum cash required in your trading account to open and maintain a leveraged contract.',
  'Pip Value': 'The exact monetary profit or loss generated by a 1-pip price movement for your position size.',
  'Leverage': 'Borrowed trading power (e.g. 1:500) allowing you to control large positions with small initial capital.',
  'Lot Size': 'Standard trading volume unit. 1.00 Lot = 100,000 base currency units or 100 oz Gold.',
  'ECN Execution': 'Direct electronic bridging to Tier-1 banks providing ultra-fast order fills with zero dealer intervention.',
  'Spread': 'The difference between the Bid (sell) price and Ask (buy) price measured in pips.',
  'Economic Calendar': 'Schedule of high-impact macroeconomic events (NFP, CPI, Interest Rates) impacting prices.',
  'Stop Out': 'Automated safety liquidation triggered if account Margin Level falls below 50%.'
};

export function FinancialTooltip({ term }: { term: string }) {
  const [isOpen, setIsOpen] = useState(false);
  const definition = FINANCIAL_GLOSSARY[term] || 'Technical financial term.';

  return (
    <span className="relative inline-flex items-center gap-1 group cursor-pointer">
      <span className="font-extrabold text-slate-800 border-b border-dashed border-slate-400 group-hover:border-brand-red transition">
        {term}
      </span>
      <HelpCircle className="w-3.5 h-3.5 text-slate-400 group-hover:text-brand-red transition shrink-0" onClick={() => setIsOpen(!isOpen)} />
      
      <span className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 w-64 p-3 bg-slate-900 text-white text-xs font-normal rounded-xl shadow-xl border border-slate-700 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-50 leading-relaxed">
        <strong className="block font-black text-brand-yellow mb-1">{term}</strong>
        {definition}
      </span>
    </span>
  );
}

interface ToolsViewProps {
  quotes?: Record<string, MarketQuote>;
  showToast?: (msg: string, type: 'success' | 'error' | 'info') => void;
}

interface MasterTrader {
  id: string;
  name: string;
  handle: string;
  avatarUrl: string;
  country: string;
  countryFlag: string;
  badge: string;
  roiYear: number;
  winRate: number;
  copiers: number;
  riskScore: number;
  maxDrawdown: number;
  allocatedCapitalTotal: string;
  strategy: string;
  assetFocus: string;
  monthlyPerformance: number[];
  openPositions: {
    symbol: string;
    type: 'BUY' | 'SELL';
    volume: number;
    entryPrice: number;
    floatingPnL: number;
  }[];
}

const TOP_MASTER_TRADERS: MasterTrader[] = [];

export default function ToolsView({ quotes, showToast }: ToolsViewProps) {
  // Calculator State
  const [calcType, setCalcType] = useState<'margin' | 'pip' | 'position'>('margin');
  const [calcSymbol, setCalcSymbol] = useState<string>('EURUSD');
  const [calcLots, setCalcLots] = useState<number>(1.0);
  const [calcLeverage, setCalcLeverage] = useState<number>(500);

  // Standalone Currency Converter State
  const [convAmount, setConvAmount] = useState<number>(1000);
  const [fromCurr, setFromCurr] = useState<string>('EUR');
  const [toCurr, setToCurr] = useState<string>('USD');
  const [copiedConv, setCopiedConv] = useState<boolean>(false);

  // Copy Trading State
  const [copyFilterCategory, setCopyFilterCategory] = useState<'all' | 'roi' | 'lowrisk' | 'copiers'>('all');
  const [selectedTraderForAnalysis, setSelectedTraderForAnalysis] = useState<MasterTrader | null>(null);
  const [copyModalTrader, setCopyModalTrader] = useState<MasterTrader | null>(null);
  const [copyCapitalAmount, setCopyCapitalAmount] = useState<number>(1000);
  const [copyStopLossPercent, setCopyStopLossPercent] = useState<number>(20);
  const [copiedTraderIds, setCopiedTraderIds] = useState<Record<string, { capital: number; stopLoss: number; date: string }>>({});

  // Academy Quiz State
  const [selectedCourseId, setSelectedCourseId] = useState<string>(ACADEMY_COURSES[0].id);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [quizSubmitted, setQuizSubmitted] = useState<boolean>(false);
  const [quizScore, setQuizScore] = useState<Record<string, 'CORRECT' | 'WRONG' | null>>({});

  // Economic Calendar Filter State
  const [impactFilter, setImpactFilter] = useState<'ALL' | 'HIGH' | 'MEDIUM' | 'LOW'>('ALL');
  const [currencyFilter, setCurrencyFilter] = useState<string>('ALL');
  const [activeAlerts, setActiveAlerts] = useState<Record<string, boolean>>({});
  const [calendarToast, setCalendarToast] = useState<string | null>(null);

  const triggerCalendarToast = (msg: string) => {
    setCalendarToast(msg);
    setTimeout(() => setCalendarToast(null), 4000);
  };

  const activeCourse = ACADEMY_COURSES.find(c => c.id === selectedCourseId) || ACADEMY_COURSES[0];

  // Standalone Currency Converter Calculations
  const CURRENCY_LIST = [
    { code: 'USD', name: 'US Dollar', flag: '🇺🇸', symbol: '$', rateInUSD: 1.0 },
    { code: 'EUR', name: 'Euro', flag: '🇪🇺', symbol: '€', rateInUSD: quotes?.['EURUSD']?.price || DEFAULT_MARKET_QUOTES['EURUSD']?.price || 1.0482 },
    { code: 'GBP', name: 'British Pound', flag: '🇬🇧', symbol: '£', rateInUSD: quotes?.['GBPUSD']?.price || DEFAULT_MARKET_QUOTES['GBPUSD']?.price || 1.2590 },
    { code: 'JPY', name: 'Japanese Yen', flag: '🇯🇵', symbol: '¥', rateInUSD: quotes?.['USDJPY'] ? (1 / quotes['USDJPY'].price) : (1 / (DEFAULT_MARKET_QUOTES['USDJPY']?.price || 154.60)) },
    { code: 'AUD', name: 'Australian Dollar', flag: '🇦🇺', symbol: 'A$', rateInUSD: quotes?.['AUDUSD']?.price || DEFAULT_MARKET_QUOTES['AUDUSD']?.price || 0.6385 },
    { code: 'CAD', name: 'Canadian Dollar', flag: '🇨🇦', symbol: 'C$', rateInUSD: quotes?.['USDCAD'] ? (1 / quotes['USDCAD'].price) : 0.7050 },
    { code: 'CHF', name: 'Swiss Franc', flag: '🇨🇭', symbol: 'Fr', rateInUSD: quotes?.['USDCHF'] ? (1 / quotes['USDCHF'].price) : 1.1080 },
    { code: 'NZD', name: 'New Zealand Dollar', flag: '🇳🇿', symbol: 'NZ$', rateInUSD: quotes?.['NZDUSD']?.price || DEFAULT_MARKET_QUOTES['NZDUSD']?.price || 0.5730 },
    { code: 'CNH', name: 'Chinese Yuan', flag: '🇨🇳', symbol: '¥', rateInUSD: 0.1380 },
    { code: 'SGD', name: 'Singapore Dollar', flag: '🇸🇬', symbol: 'S$', rateInUSD: 0.7420 },
    { code: 'XAU', name: 'Gold Spot (1 oz)', flag: '🥇', symbol: 'oz', rateInUSD: quotes?.['XAUUSD']?.price || DEFAULT_MARKET_QUOTES['XAUUSD']?.price || 2915.40 },
    { code: 'BTC', name: 'Bitcoin (Spot)', flag: '₿', symbol: '₿', rateInUSD: quotes?.['BTCUSD']?.price || DEFAULT_MARKET_QUOTES['BTCUSD']?.price || 96450.00 },
  ];

  const getRateInUSD = (code: string): number => {
    const found = CURRENCY_LIST.find(c => c.code === code);
    return found ? found.rateInUSD : 1.0;
  };

  const getCurrencySymbol = (code: string): string => {
    const found = CURRENCY_LIST.find(c => c.code === code);
    return found ? found.symbol : '$';
  };

  const getCurrencyFlag = (code: string): string => {
    const found = CURRENCY_LIST.find(c => c.code === code);
    return found ? found.flag : '🌐';
  };

  const fromRateInUSD = getRateInUSD(fromCurr);
  const toRateInUSD = getRateInUSD(toCurr);

  // 1 FROM = X TO
  const unitExchangeRate = fromRateInUSD / toRateInUSD;
  // 1 TO = Y FROM
  const inverseExchangeRate = toRateInUSD / fromRateInUSD;

  const totalConverted = (convAmount || 0) * unitExchangeRate;

  const handleSwapCurrencies = () => {
    const temp = fromCurr;
    setFromCurr(toCurr);
    setToCurr(temp);
  };

  const handleCopyResult = () => {
    const text = `${convAmount.toLocaleString()} ${fromCurr} = ${totalConverted.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 4 })} ${toCurr}`;
    if (navigator?.clipboard) {
      navigator.clipboard.writeText(text);
    }
    setCopiedConv(true);
    if (showToast) showToast(`Copied to clipboard: ${text}`, 'success');
    setTimeout(() => setCopiedConv(false), 2500);
  };

  // Live calculator math
  const getSymbolBasePrice = (sym: string): number => {
    return DEFAULT_MARKET_QUOTES[sym]?.price || 1.0482;
  };

  const getContractMultiplier = (sym: string): number => {
    if (sym === 'BTCUSD') return 1;
    if (sym === 'XAUUSD') return 100;
    return 100000; // Standard FX Lot
  };

  const calculateMargin = (): number => {
    const price = getSymbolBasePrice(calcSymbol);
    const multiplier = getContractMultiplier(calcSymbol);
    return Number(((price * calcLots * multiplier) / calcLeverage).toFixed(2));
  };

  const calculatePipValue = (): number => {
    const multiplier = getContractMultiplier(calcSymbol);
    const pipSize = calcSymbol === 'USDJPY' ? 0.01 : 0.0001;
    return Number((calcLots * multiplier * pipSize).toFixed(2));
  };

  const handleQuizAnswer = (idx: number) => {
    if (quizSubmitted) return;
    setSelectedAnswer(idx);
  };

  const submitQuiz = () => {
    if (selectedAnswer === null) return;
    setQuizSubmitted(true);
    const isCorrect = selectedAnswer === activeCourse.quiz.correctIndex;
    setQuizScore(prev => ({
      ...prev,
      [selectedCourseId]: isCorrect ? 'CORRECT' : 'WRONG'
    }));
  };

  const resetQuiz = () => {
    setSelectedAnswer(null);
    setQuizSubmitted(false);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10 flex flex-col gap-12 bg-brand-light">
      
      {/* Intro Header */}
      <div className="text-center max-w-3xl mx-auto flex flex-col items-center gap-3">
        <span className="text-brand-red text-xs font-black tracking-widest uppercase bg-brand-red/5 border border-brand-red/10 px-3.5 py-1.5 rounded-full">
          Smart Tools & Resources
        </span>
        <h1 className="text-3xl md:text-4xl font-black text-brand-dark tracking-tight animate-fade-in">
          Axi Calculations & Learning Portals
        </h1>
        <p className="text-slate-500 text-xs sm:text-sm font-semibold">
          Optimize trade allocation, compute required risk reserves, or master technical indicators with interactive certifications.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
        
        {/* Left Column: Interactive Calculators (Col span 6) */}
        <div className="lg:col-span-6 bg-white border border-slate-200 rounded-2xl p-6 flex flex-col gap-6 shadow-sm">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <h3 className="text-sm font-black text-brand-dark flex items-center gap-2 uppercase tracking-wider">
              <Calculator className="w-5 h-5 text-brand-red" /> Real-Time CFD Calculators
            </h3>
            
            {/* Calc Selection Switch */}
            <div className="bg-slate-100 border border-slate-200 rounded-xl p-1 flex gap-1 shadow-inner">
              <button
                onClick={() => { setCalcType('margin'); setCalcSymbol('EURUSD'); }}
                className={`px-3 py-1.5 text-[10px] font-black uppercase rounded-lg tracking-wider transition-all duration-150 ${
                  calcType === 'margin' ? 'bg-brand-red text-white shadow-sm' : 'text-slate-500 hover:text-brand-red'
                }`}
              >
                Margin
              </button>
              <button
                onClick={() => { setCalcType('pip'); setCalcSymbol('EURUSD'); }}
                className={`px-3 py-1.5 text-[10px] font-black uppercase rounded-lg tracking-wider transition-all duration-150 ${
                  calcType === 'pip' ? 'bg-brand-red text-white shadow-sm' : 'text-slate-500 hover:text-brand-red'
                }`}
              >
                Pip Values
              </button>
              <button
                onClick={() => { setCalcType('position'); setCalcSymbol('EURUSD'); }}
                className={`px-3 py-1.5 text-[10px] font-black uppercase rounded-lg tracking-wider transition-all duration-150 ${
                  calcType === 'position' ? 'bg-brand-red text-white shadow-sm' : 'text-slate-500 hover:text-brand-red'
                }`}
              >
                Position Size
              </button>
            </div>
          </div>

          {calcType === 'position' ? (
            <PositionSizeCalculator />
          ) : (
            <>
          <div className="flex flex-col gap-4 text-xs font-bold text-slate-600">
            
            {/* Symbol Selection */}
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] uppercase font-black text-slate-400 tracking-wider">Asset class symbol</label>
              <select
                value={calcSymbol}
                onChange={(e) => setCalcSymbol(e.target.value)}
                className="bg-slate-50 border border-slate-200 focus:border-brand-red focus:bg-white rounded-lg px-3.5 py-2.5 text-slate-800 font-extrabold focus:outline-none transition shadow-sm"
              >
                <option value="EURUSD">EUR/USD (Euro Dollar)</option>
                <option value="GBPUSD">GBP/USD (Pound Dollar)</option>
                <option value="USDJPY">USD/JPY (Dollar Yen)</option>
                <option value="BTCUSD">BTC/USD (Bitcoin CFD)</option>
                <option value="XAUUSD">XAU/USD (Gold CFD)</option>
              </select>
            </div>

            {/* Lot size input */}
            <div className="flex flex-col gap-1.5">
              <label className="text-[10px] uppercase font-black text-slate-400 tracking-wider">Trade Size (Lots)</label>
              <input
                type="number"
                step="0.01"
                min="0.01"
                max="50.0"
                value={calcLots}
                onChange={(e) => setCalcLots(Number(e.target.value))}
                className="bg-slate-50 border border-slate-200 focus:border-brand-red focus:bg-white rounded-lg px-3.5 py-2.5 text-slate-800 font-mono font-black focus:outline-none transition shadow-sm"
              />
            </div>

            {/* Leverage select (only for margin calc) */}
            {calcType === 'margin' && (
              <div className="flex flex-col gap-1.5">
                <label className="text-[10px] uppercase font-black text-slate-400 tracking-wider">Account Leverage ratio</label>
                <select
                  value={calcLeverage}
                  onChange={(e) => setCalcLeverage(Number(e.target.value))}
                  className="bg-slate-50 border border-slate-200 focus:border-brand-red focus:bg-white rounded-lg px-3.5 py-2.5 text-slate-800 font-mono focus:outline-none transition shadow-sm"
                >
                  <option value={100}>1:100 leverage</option>
                  <option value={200}>1:200 leverage</option>
                  <option value={500}>1:500 Axi max leverage</option>
                </select>
              </div>
            )}

          </div>

          {/* Calculator Output Card */}
          <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl flex items-center justify-between shadow-inner">
            <div className="flex flex-col">
              <span className="text-[10px] uppercase font-black text-slate-400 tracking-wider">
                {calcType === 'margin' ? 'ESTIMATED MARGIN REQUIREMENT' : 'ESTIMATED PIP VALUE IN USD'}
              </span>
              <span className="text-brand-red text-3xl font-mono font-black mt-1">
                USD ${calcType === 'margin' ? calculateMargin().toLocaleString() : calculatePipValue().toLocaleString()}
              </span>
            </div>
            <div className="w-12 h-12 rounded-xl bg-brand-red/5 text-brand-red border border-brand-red/10 flex items-center justify-center shadow-sm">
              <Zap className="w-6 h-6 text-brand-red" />
            </div>
          </div>

          <div className="text-[10px] text-slate-500 font-semibold leading-relaxed bg-brand-red/5 border border-brand-red/10 p-3.5 rounded-xl">
            Calculations are based on live market index variables (EURUSD = 1.0845). Spreads or trade fees are not integrated into basic reserve calculations. Always size trades responsibly.
          </div>
            </>
          )}
        </div>

        {/* Right Column: Academy Quiz Portal (Col span 6) */}
        <div className="lg:col-span-6 bg-white border border-slate-200 rounded-2xl p-6 flex flex-col gap-6 shadow-sm">
          <div className="flex items-center justify-between border-b border-slate-100 pb-3">
            <h3 className="text-sm font-black text-brand-dark flex items-center gap-2 uppercase tracking-wider">
              <BookOpen className="w-5 h-5 text-brand-red" /> Axi Academy Quiz Center
            </h3>
            
            {/* Score Tracker Badge */}
            <span className="text-[10px] font-black text-brand-red bg-brand-red/5 border border-brand-red/10 px-3 py-1 rounded-md uppercase tracking-wider">
              Certified Courses
            </span>
          </div>

          {/* Course select sidebar links */}
          <div className="flex gap-2.5 overflow-x-auto pb-1.5">
            {ACADEMY_COURSES.map((course) => {
              const score = quizScore[course.id];
              return (
                <button
                  key={course.id}
                  onClick={() => {
                    setSelectedCourseId(course.id);
                    resetQuiz();
                  }}
                  className={`px-3.5 py-2.5 rounded-xl text-left border flex flex-col gap-0.5 shrink-0 transition-all duration-150 ${
                    selectedCourseId === course.id 
                      ? 'bg-slate-50 border-brand-red text-brand-red shadow-sm' 
                      : 'bg-white border-slate-200 hover:border-slate-300 text-slate-500'
                  }`}
                >
                  <span className="text-[10px] font-black">{course.title}</span>
                  <div className="flex items-center gap-2 text-[8px] font-black mt-1 uppercase tracking-wider text-slate-400">
                    <span>{course.duration}</span>
                    <span>•</span>
                    <span className={`${score === 'CORRECT' ? 'text-emerald-600' : score === 'WRONG' ? 'text-brand-red' : ''}`}>
                      {score ? score : 'Not started'}
                    </span>
                  </div>
                </button>
              );
            })}
          </div>

          {/* Active Quiz Card */}
          <div className="bg-slate-50 border border-slate-200 p-5 rounded-2xl flex flex-col gap-5">
            <div className="flex flex-col gap-1">
              <span className="text-[9px] uppercase font-black text-slate-400 tracking-wider">Active Course Module</span>
              <h4 className="text-sm font-black text-brand-dark">{activeCourse.title}</h4>
              <p className="text-slate-500 text-xs font-semibold mt-1 leading-relaxed">{activeCourse.description}</p>
            </div>

            {/* Multiple Choice Options */}
            <div className="flex flex-col gap-2">
              <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-1">
                Course validation question:
              </span>
              <p className="text-xs font-black text-slate-800 mb-2 leading-relaxed">
                {activeCourse.quiz.question}
              </p>

              <div className="flex flex-col gap-2">
                {activeCourse.quiz.options.map((opt, idx) => {
                  const isSelected = selectedAnswer === idx;
                  const isCorrectAnswer = idx === activeCourse.quiz.correctIndex;
                  
                  let optionStyle = 'bg-white border-slate-200 hover:border-slate-300 text-slate-700 font-extrabold';
                  if (isSelected && !quizSubmitted) {
                    optionStyle = 'bg-brand-red/5 border-brand-red text-brand-red font-black';
                  } else if (quizSubmitted) {
                    if (isCorrectAnswer) {
                      optionStyle = 'bg-emerald-50 border-emerald-500 text-emerald-800 font-black';
                    } else if (isSelected) {
                      optionStyle = 'bg-rose-50 border-rose-500 text-rose-850 font-black';
                    } else {
                      optionStyle = 'bg-slate-100 border-slate-200 text-slate-400 pointer-events-none font-bold';
                    }
                  }

                  return (
                    <button
                      key={idx}
                      onClick={() => handleQuizAnswer(idx)}
                      disabled={quizSubmitted}
                      className={`w-full text-left p-3.5 rounded-xl border text-xs leading-relaxed transition flex items-center justify-between shadow-sm ${optionStyle}`}
                    >
                      <span>{opt}</span>
                      {quizSubmitted && isCorrectAnswer && (
                        <Check className="w-4 h-4 text-emerald-600 shrink-0 stroke-[3]" />
                      )}
                      {quizSubmitted && isSelected && !isCorrectAnswer && (
                        <X className="w-4 h-4 text-brand-red shrink-0 stroke-[3]" />
                      )}
                    </button>
                  );
                })}

              </div>
            </div>

            {/* Submit and Feedback Panel */}
            <div className="border-t border-slate-200 pt-4 flex flex-col gap-3">
              {!quizSubmitted ? (
                <motion.button
                  whileHover={{ scale: 1.03 }}
                  whileTap={{ scale: 0.97 }}
                  onClick={submitQuiz}
                  disabled={selectedAnswer === null}
                  className="w-full py-3.5 bg-brand-red disabled:bg-slate-200 disabled:text-slate-400 hover:bg-brand-red-hover text-white text-xs font-black uppercase rounded-xl transition flex items-center justify-center gap-1.5 shadow-md shadow-brand-red/10 cursor-pointer"
                >
                  Submit Answer <ChevronRight className="w-4 h-4 text-brand-yellow stroke-[3]" />
                </motion.button>
              ) : (
                <div className="flex flex-col gap-3">
                  <div className={`p-4 rounded-xl border text-xs leading-relaxed font-semibold ${
                    selectedAnswer === activeCourse.quiz.correctIndex 
                      ? 'bg-emerald-50 border-emerald-200 text-emerald-800' 
                      : 'bg-rose-50 border-rose-250 text-rose-800'
                  }`}>
                    <strong className="block text-sm font-black mb-1">
                      {selectedAnswer === activeCourse.quiz.correctIndex ? 'Excellent! Correct answer.' : 'Incorrect. Try reviewing the explanation below.'}
                    </strong>
                    <p className="mt-1 text-slate-600 leading-relaxed text-[11px] font-bold">{activeCourse.quiz.explanation}</p>
                  </div>

                  <motion.button
                    whileHover={{ scale: 1.04 }}
                    whileTap={{ scale: 0.96 }}
                    onClick={resetQuiz}
                    className="bg-white hover:bg-slate-50 border border-slate-200 text-slate-600 font-extrabold text-xs py-2.5 px-4 rounded-xl transition flex items-center justify-center gap-1.5 self-end shadow-sm cursor-pointer"
                  >
                    <RefreshCcw className="w-3.5 h-3.5 text-brand-red" /> Retry Module
                  </motion.button>
                </div>
              )}
            </div>

          </div>

        </div>

      </div>

      {/* SECTION: STANDALONE LIVE CURRENCY CONVERTER */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 sm:p-8 flex flex-col gap-6 shadow-sm">
        
        {/* Converter Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 dark:border-slate-800 pb-4">
          <div className="flex items-center gap-3">
            <div className="w-11 h-11 rounded-2xl bg-brand-red/10 text-brand-red border border-brand-red/20 flex items-center justify-center shadow-xs shrink-0">
              <ArrowLeftRight className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-base font-black text-brand-dark dark:text-white uppercase tracking-wider">
                  Standalone Currency Converter
                </h3>
                <span className="bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 text-[10px] font-black px-2 py-0.5 rounded-md border border-emerald-500/20 uppercase tracking-widest flex items-center gap-1">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
                  Live Feed
                </span>
              </div>
              <p className="text-slate-500 dark:text-slate-400 text-xs font-semibold mt-0.5">
                Convert live exchange values across 12 major currencies, spot gold, and cryptocurrencies with zero institutional markup.
              </p>
            </div>
          </div>

          {/* Quick Popular Pairs Chips */}
          <div className="flex flex-wrap items-center gap-1.5">
            <span className="text-[10px] font-black uppercase text-slate-400 mr-1">Popular:</span>
            {[
              { label: 'EUR/USD', from: 'EUR', to: 'USD' },
              { label: 'GBP/USD', from: 'GBP', to: 'USD' },
              { label: 'USD/JPY', from: 'USD', to: 'JPY' },
              { label: 'AUD/USD', from: 'AUD', to: 'USD' },
              { label: 'USD/CAD', from: 'USD', to: 'CAD' },
              { label: 'XAU/USD', from: 'XAU', to: 'USD' },
              { label: 'BTC/USD', from: 'BTC', to: 'USD' },
            ].map((p) => (
              <button
                key={p.label}
                onClick={() => { setFromCurr(p.from); setToCurr(p.to); }}
                className={`px-2.5 py-1 text-[10px] font-mono font-black rounded-lg border transition-all cursor-pointer ${
                  fromCurr === p.from && toCurr === p.to
                    ? 'bg-brand-red text-white border-brand-red shadow-xs'
                    : 'bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-300 border-slate-200 dark:border-slate-700 hover:border-brand-red'
                }`}
              >
                {p.label}
              </button>
            ))}
          </div>
        </div>

        {/* Interactive Converter Form */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-center">
          
          {/* Amount Input Column */}
          <div className="lg:col-span-4 flex flex-col gap-2">
            <label className="text-[10px] font-black uppercase text-slate-400 tracking-wider flex justify-between">
              <span>Amount to Convert</span>
              <span className="text-brand-red font-mono font-extrabold">{getCurrencySymbol(fromCurr)} {convAmount.toLocaleString()}</span>
            </label>
            <div className="relative">
              <span className="absolute left-3.5 top-1/2 -translate-y-1/2 text-slate-400 font-mono font-bold text-sm">
                {getCurrencySymbol(fromCurr)}
              </span>
              <input
                type="number"
                min="0.01"
                step="any"
                value={convAmount}
                onChange={(e) => setConvAmount(Math.max(0, Number(e.target.value)))}
                className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 focus:border-brand-red focus:bg-white dark:focus:bg-slate-900 rounded-xl pl-9 pr-4 py-3 text-slate-900 dark:text-white font-mono font-black text-lg focus:outline-none transition shadow-xs"
                placeholder="1,000"
              />
            </div>

            {/* Quick Amount Presets */}
            <div className="flex items-center gap-1.5 mt-1 overflow-x-auto pb-1">
              {[100, 500, 1000, 5000, 10000, 50000].map((amt) => (
                <button
                  key={amt}
                  onClick={() => setConvAmount(amt)}
                  className={`px-2 py-0.5 text-[9px] font-mono font-extrabold rounded-md border transition cursor-pointer ${
                    convAmount === amt
                      ? 'bg-slate-900 text-white dark:bg-white dark:text-slate-900 border-slate-900'
                      : 'bg-slate-100 dark:bg-slate-800 text-slate-500 border-slate-200 dark:border-slate-700 hover:text-slate-900'
                  }`}
                >
                  ${amt >= 1000 ? `${amt / 1000}k` : amt}
                </button>
              ))}
            </div>
          </div>

          {/* Currency Selectors & Swap Group */}
          <div className="lg:col-span-8 grid grid-cols-1 sm:grid-cols-11 gap-3 items-center">
            
            {/* From Currency */}
            <div className="sm:col-span-5 flex flex-col gap-1.5">
              <label className="text-[10px] font-black uppercase text-slate-400 tracking-wider">From Currency</label>
              <div className="relative">
                <select
                  value={fromCurr}
                  onChange={(e) => setFromCurr(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 focus:border-brand-red text-slate-900 dark:text-white font-extrabold text-sm py-3 pl-10 pr-8 rounded-xl focus:outline-none transition shadow-xs appearance-none cursor-pointer"
                >
                  {CURRENCY_LIST.map((c) => (
                    <option key={c.code} value={c.code}>
                      {c.flag} {c.code} - {c.name}
                    </option>
                  ))}
                </select>
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-lg pointer-events-none">
                  {getCurrencyFlag(fromCurr)}
                </span>
              </div>
            </div>

            {/* Swap Button */}
            <div className="sm:col-span-1 flex items-center justify-center pt-2 sm:pt-5">
              <motion.button
                whileHover={{ rotate: 180, scale: 1.1 }}
                whileTap={{ scale: 0.9 }}
                onClick={handleSwapCurrencies}
                className="w-10 h-10 rounded-full bg-brand-red text-white flex items-center justify-center shadow-md hover:bg-brand-red-hover transition cursor-pointer border-2 border-white dark:border-slate-900"
                title="Swap From and To currencies"
              >
                <ArrowLeftRight className="w-4 h-4 stroke-[2.5]" />
              </motion.button>
            </div>

            {/* To Currency */}
            <div className="sm:col-span-5 flex flex-col gap-1.5">
              <label className="text-[10px] font-black uppercase text-slate-400 tracking-wider">To Currency</label>
              <div className="relative">
                <select
                  value={toCurr}
                  onChange={(e) => setToCurr(e.target.value)}
                  className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 focus:border-brand-red text-slate-900 dark:text-white font-extrabold text-sm py-3 pl-10 pr-8 rounded-xl focus:outline-none transition shadow-xs appearance-none cursor-pointer"
                >
                  {CURRENCY_LIST.map((c) => (
                    <option key={c.code} value={c.code}>
                      {c.flag} {c.code} - {c.name}
                    </option>
                  ))}
                </select>
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-lg pointer-events-none">
                  {getCurrencyFlag(toCurr)}
                </span>
              </div>
            </div>

          </div>

        </div>

        {/* Calculation Result Highlight Box */}
        <div className="bg-slate-900 dark:bg-slate-950 text-white rounded-2xl p-6 border border-slate-800 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-6 relative overflow-hidden">
          <div className="absolute top-0 right-0 w-64 h-64 bg-brand-red/10 rounded-full blur-3xl pointer-events-none"></div>

          <div className="flex flex-col gap-1 z-10">
            <span className="text-[11px] font-black uppercase tracking-widest text-slate-400 flex items-center gap-2">
              <span>{convAmount.toLocaleString()} {fromCurr} =</span>
              <span className="text-brand-yellow font-mono font-bold">Live ECN Rate</span>
            </span>

            <div className="text-3xl sm:text-4xl font-mono font-black text-white tracking-tight mt-0.5">
              {getCurrencySymbol(toCurr)} {totalConverted.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 4 })} <span className="text-xl text-brand-yellow font-sans">{toCurr}</span>
            </div>

            <div className="flex flex-wrap items-center gap-3 text-xs font-mono text-slate-400 mt-2">
              <span className="bg-slate-800/80 px-2.5 py-1 rounded-md border border-slate-700">
                1 {fromCurr} = <strong className="text-emerald-400">{unitExchangeRate.toFixed(5)}</strong> {toCurr}
              </span>
              <span className="bg-slate-800/80 px-2.5 py-1 rounded-md border border-slate-700">
                1 {toCurr} = <strong className="text-amber-400">{inverseExchangeRate.toFixed(5)}</strong> {fromCurr}
              </span>
            </div>
          </div>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 z-10">
            <button
              onClick={handleCopyResult}
              className={`px-4 py-3 rounded-xl font-black text-xs uppercase transition-all flex items-center justify-center gap-2 cursor-pointer ${
                copiedConv
                  ? 'bg-emerald-500 text-white shadow-lg'
                  : 'bg-slate-800 hover:bg-slate-700 text-slate-200 border border-slate-700'
              }`}
            >
              {copiedConv ? <Check className="w-4 h-4 text-white" /> : <Copy className="w-4 h-4 text-brand-yellow" />}
              {copiedConv ? 'Result Copied!' : 'Copy Value'}
            </button>
          </div>
        </div>

        {/* Multi-Currency Cross Rate Table Preview */}
        <div className="border border-slate-150 dark:border-slate-800 rounded-xl overflow-hidden bg-slate-50/50 dark:bg-slate-950/50 p-4">
          <div className="flex items-center justify-between mb-3">
            <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider flex items-center gap-1.5">
              <Globe className="w-3.5 h-3.5 text-brand-red" />
              Live Cross-Rates Matrix for {convAmount.toLocaleString()} {fromCurr}
            </span>
            <span className="text-[10px] text-slate-400 font-semibold">Updated Real-Time</span>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-6 gap-2">
            {CURRENCY_LIST.filter(c => c.code !== fromCurr).slice(0, 6).map((item) => {
              const itemRate = fromRateInUSD / item.rateInUSD;
              const convertedVal = convAmount * itemRate;
              return (
                <div 
                  key={item.code} 
                  onClick={() => setToCurr(item.code)}
                  className={`p-3 rounded-xl border text-left transition cursor-pointer ${
                    toCurr === item.code
                      ? 'bg-brand-red/5 border-brand-red text-brand-red'
                      : 'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800 hover:border-slate-300 dark:hover:border-slate-700 text-slate-800 dark:text-slate-200'
                  }`}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="text-xs font-black flex items-center gap-1">
                      <span>{item.flag}</span>
                      <span>{item.code}</span>
                    </span>
                    <span className="text-[9px] font-mono text-slate-400 font-bold">{itemRate.toFixed(4)}</span>
                  </div>
                  <div className="text-sm font-mono font-black truncate">
                    {item.symbol} {convertedVal.toLocaleString(undefined, { maximumFractionDigits: 2 })}
                  </div>
                </div>
              );
            })}
          </div>
        </div>

      </div>

      {/* SECTION: AXI COPY TRADING NETWORK */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 sm:p-8 flex flex-col gap-6 shadow-sm">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 dark:border-slate-800 pb-5">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-brand-red text-white flex items-center justify-center shadow-md shrink-0">
              <Users className="w-6 h-6" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-lg font-black text-brand-dark dark:text-white uppercase tracking-wider">
                  Axi Copy Trading Network
                </h3>
                <span className="bg-brand-red/10 text-brand-red text-[10px] font-black px-2 py-0.5 rounded-md border border-brand-red/20 uppercase tracking-widest flex items-center gap-1">
                  <Award className="w-3 h-3 text-brand-red" />
                  Institutional Copy
                </span>
              </div>
              <p className="text-slate-500 dark:text-slate-400 text-xs font-semibold mt-0.5">
                Automatically mirror positions from top-performing strategy managers with zero slippage and full risk controls.
              </p>
            </div>
          </div>

          {/* Active Copied Summary Pill */}
          <div className="bg-slate-50 dark:bg-slate-800/80 p-3 rounded-xl border border-slate-200 dark:border-slate-700 flex items-center gap-4">
            <div className="flex flex-col">
              <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider">Active Copy Accounts</span>
              <span className="text-sm font-black text-slate-900 dark:text-white font-mono">
                {Object.keys(copiedTraderIds).length} Master Trader{Object.keys(copiedTraderIds).length !== 1 ? 's' : ''}
              </span>
            </div>
            <div className="h-8 w-px bg-slate-200 dark:bg-slate-700" />
            <div className="flex flex-col">
              <span className="text-[10px] font-black uppercase text-slate-400 tracking-wider">Total Copy Capital</span>
              <span className="text-sm font-black text-emerald-500 font-mono">
                ${(Object.values(copiedTraderIds) as { capital: number; stopLoss: number }[]).reduce((acc, c) => acc + c.capital, 0).toLocaleString()}
              </span>
            </div>
          </div>
        </div>

        {/* Active Copied Traders Panel */}
        {Object.keys(copiedTraderIds).length > 0 && (
          <div className="bg-emerald-500/5 border border-emerald-500/20 rounded-xl p-4 flex flex-col gap-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-black uppercase tracking-wider text-emerald-600 dark:text-emerald-400 flex items-center gap-1.5">
                <UserCheck className="w-4 h-4" />
                Active Replicated Strategies ({Object.keys(copiedTraderIds).length})
              </span>
              <span className="text-[10px] font-bold text-slate-400">Real-time MT5 Integration</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {(Object.entries(copiedTraderIds) as [string, { capital: number; stopLoss: number; date: string }][]).map(([traderId, copyInfo]) => {
                const master = TOP_MASTER_TRADERS.find(t => t.id === traderId);
                if (!master) return null;

                const estFloatingProfit = master.openPositions.reduce((acc, pos) => acc + pos.floatingPnL, 0) * (copyInfo.capital / 1000);

                return (
                  <div key={traderId} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-3.5 flex items-center justify-between gap-3 shadow-xs">
                    <div className="flex items-center gap-3">
                      <img src={master.avatarUrl} alt={master.name} className="w-10 h-10 rounded-full object-cover border-2 border-emerald-500" />
                      <div className="flex flex-col">
                        <span className="text-xs font-black text-slate-900 dark:text-white flex items-center gap-1">
                          {master.name} <span className="text-sm">{master.countryFlag}</span>
                        </span>
                        <span className="text-[10px] text-slate-400 font-mono">
                          Allocated: <strong className="text-slate-700 dark:text-slate-200">${copyInfo.capital.toLocaleString()}</strong> | SL: {copyInfo.stopLoss}%
                        </span>
                      </div>
                    </div>

                    <div className="flex items-center gap-3">
                      <div className="text-right">
                        <span className="text-[9px] font-black uppercase text-slate-400 block">Floating P&L</span>
                        <span className={`text-xs font-black font-mono ${estFloatingProfit >= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
                          {estFloatingProfit >= 0 ? '+' : ''}${estFloatingProfit.toFixed(2)}
                        </span>
                      </div>

                      <button
                        onClick={() => {
                          setCopiedTraderIds(prev => {
                            const next = { ...prev };
                            delete next[traderId];
                            return next;
                          });
                          if (showToast) showToast(`Stopped copying ${master.name}. Replicated orders closed.`, 'info');
                        }}
                        className="px-2.5 py-1.5 text-[10px] font-bold text-rose-600 dark:text-rose-400 hover:bg-rose-50 dark:hover:bg-rose-950/40 rounded-lg border border-rose-200 dark:border-rose-900 transition cursor-pointer"
                      >
                        Stop Copying
                      </button>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Directory Controls / Category Filters */}
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
          <div className="flex items-center gap-1.5 overflow-x-auto pb-1 max-w-full">
            {[
              { id: 'all', label: 'All Master Traders' },
              { id: 'roi', label: '🔥 Top ROI (+200%+)' },
              { id: 'lowrisk', label: '🛡 Low Risk (Score ≤ 3)' },
              { id: 'copiers', label: '👥 Most Copied (2,000+)' },
            ].map(f => (
              <button
                key={f.id}
                onClick={() => setCopyFilterCategory(f.id as any)}
                className={`px-3 py-1.5 text-xs font-extrabold rounded-lg border transition whitespace-nowrap cursor-pointer ${
                  copyFilterCategory === f.id
                    ? 'bg-brand-red text-white border-brand-red shadow-xs'
                    : 'bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-300 border-slate-200 dark:border-slate-700 hover:border-slate-400'
                }`}
              >
                {f.label}
              </button>
            ))}
          </div>

          <span className="text-[11px] font-bold text-slate-400">
            Showing {TOP_MASTER_TRADERS.length} Verified Managers
          </span>
        </div>

        {/* Master Traders Cards Grid */}
        {TOP_MASTER_TRADERS.length === 0 ? (
          <div className="bg-slate-50 dark:bg-slate-900/50 rounded-2xl border border-slate-200 dark:border-slate-800 p-8 text-center flex flex-col items-center justify-center space-y-3">
            <Users className="w-10 h-10 text-slate-400 dark:text-slate-600" />
            <h4 className="text-base font-black text-slate-800 dark:text-slate-200">No Master Traders Currently Registered</h4>
            <p className="text-xs text-slate-500 dark:text-slate-400 max-w-md">
              To guarantee transparency and genuine performance, master traders must connect their verified live trading accounts and pass risk verification before strategies are published to the copy pool.
            </p>
          </div>
        ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {TOP_MASTER_TRADERS.filter(trader => {
            if (copyFilterCategory === 'roi') return trader.roiYear >= 200;
            if (copyFilterCategory === 'lowrisk') return trader.riskScore <= 3;
            if (copyFilterCategory === 'copiers') return trader.copiers >= 2000;
            return true;
          }).map((trader) => {
            const isCurrentlyCopied = !!copiedTraderIds[trader.id];

            return (
              <div
                key={trader.id}
                className={`rounded-2xl border p-5 flex flex-col justify-between gap-4 transition-all duration-200 hover:shadow-md ${
                  isCurrentlyCopied
                    ? 'bg-emerald-500/5 border-emerald-500/30'
                    : 'bg-slate-50/50 dark:bg-slate-950/50 border-slate-200 dark:border-slate-800 hover:border-brand-red/40'
                }`}
              >
                {/* Top Trader Info */}
                <div className="flex items-start justify-between gap-3">
                  <div className="flex items-center gap-3">
                    <div className="relative">
                      <img
                        src={trader.avatarUrl}
                        alt={trader.name}
                        className="w-12 h-12 rounded-2xl object-cover border-2 border-white dark:border-slate-800 shadow-xs"
                      />
                      <span className="absolute -bottom-1 -right-1 text-base">{trader.countryFlag}</span>
                    </div>

                    <div className="flex flex-col">
                      <div className="flex items-center gap-2">
                        <h4 className="text-sm font-black text-slate-900 dark:text-white">
                          {trader.name}
                        </h4>
                        <span className="bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-300 text-[9px] font-black px-2 py-0.5 rounded uppercase">
                          {trader.badge}
                        </span>
                      </div>
                      <span className="text-[11px] font-mono text-slate-400">{trader.handle}</span>
                    </div>
                  </div>

                  {/* Risk Badge */}
                  <div className="flex flex-col items-end">
                    <span className="text-[9px] font-black uppercase text-slate-400">Risk Score</span>
                    <span className={`px-2 py-0.5 rounded text-[10px] font-black font-mono ${
                      trader.riskScore <= 3 
                        ? 'bg-emerald-500/10 text-emerald-500 border border-emerald-500/20' 
                        : trader.riskScore <= 5 
                        ? 'bg-amber-500/10 text-amber-500 border border-amber-500/20' 
                        : 'bg-rose-500/10 text-rose-500 border border-rose-500/20'
                    }`}>
                      {trader.riskScore}/10 ({trader.riskScore <= 3 ? 'Low' : trader.riskScore <= 5 ? 'Medium' : 'High'})
                    </span>
                  </div>
                </div>

                {/* Key Metrics Row */}
                <div className="grid grid-cols-4 gap-2 bg-white dark:bg-slate-900 p-3 rounded-xl border border-slate-150 dark:border-slate-800">
                  <div className="flex flex-col">
                    <span className="text-[9px] font-black uppercase text-slate-400">1Y Gain</span>
                    <span className="text-sm font-black text-emerald-500 font-mono">+{trader.roiYear}%</span>
                  </div>
                  <div className="flex flex-col">
                    <span className="text-[9px] font-black uppercase text-slate-400">Win Rate</span>
                    <span className="text-sm font-black text-slate-800 dark:text-slate-200 font-mono">{trader.winRate}%</span>
                  </div>
                  <div className="flex flex-col">
                    <span className="text-[9px] font-black uppercase text-slate-400">Copiers</span>
                    <span className="text-sm font-black text-slate-800 dark:text-slate-200 font-mono">{trader.copiers.toLocaleString()}</span>
                  </div>
                  <div className="flex flex-col">
                    <span className="text-[9px] font-black uppercase text-slate-400">Max DD</span>
                    <span className="text-sm font-black text-rose-500 font-mono">{trader.maxDrawdown}%</span>
                  </div>
                </div>

                {/* Strategy Snippet */}
                <div className="text-xs text-slate-600 dark:text-slate-300 font-medium line-clamp-2">
                  <span className="font-extrabold text-slate-900 dark:text-white">Strategy: </span>
                  {trader.strategy} — <span className="text-slate-400">Focus: {trader.assetFocus}</span>
                </div>

                {/* Monthly Performance Mini Bar Chart */}
                <div className="flex flex-col gap-1">
                  <span className="text-[9px] font-black uppercase text-slate-400">12-Month Performance Trend</span>
                  <div className="flex items-end gap-1 h-8 bg-white dark:bg-slate-900 p-1.5 rounded-lg border border-slate-150 dark:border-slate-800">
                    {trader.monthlyPerformance.map((m, idx) => (
                      <div
                        key={idx}
                        title={`Month ${idx + 1}: ${m >= 0 ? '+' : ''}${m}%`}
                        className={`flex-1 rounded-xs transition-all ${
                          m >= 0 ? 'bg-emerald-500 hover:bg-emerald-400' : 'bg-rose-500 hover:bg-rose-400'
                        }`}
                        style={{ height: `${Math.min(100, Math.max(15, Math.abs(m) * 2.5))}%` }}
                      />
                    ))}
                  </div>
                </div>

                {/* Actions Footer */}
                <div className="flex items-center gap-2 pt-2 border-t border-slate-200/60 dark:border-slate-800">
                  <button
                    onClick={() => setSelectedTraderForAnalysis(trader)}
                    className="flex-1 py-2.5 px-3 bg-white dark:bg-slate-800 hover:bg-slate-100 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-black text-xs rounded-xl border border-slate-200 dark:border-slate-700 transition flex items-center justify-center gap-1.5 cursor-pointer"
                  >
                    <BarChart3 className="w-3.5 h-3.5 text-brand-red" />
                    Analyze Stats
                  </button>

                  <button
                    onClick={() => {
                      setCopyModalTrader(trader);
                      setCopyCapitalAmount(1000);
                      setCopyStopLossPercent(20);
                    }}
                    className={`flex-1 py-2.5 px-3 font-black text-xs rounded-xl transition flex items-center justify-center gap-1.5 cursor-pointer shadow-xs ${
                      isCurrentlyCopied
                        ? 'bg-emerald-600 hover:bg-emerald-700 text-white'
                        : 'bg-brand-red hover:bg-brand-red-hover text-white'
                    }`}
                  >
                    {isCurrentlyCopied ? <UserCheck className="w-3.5 h-3.5" /> : <Play className="w-3.5 h-3.5" />}
                    {isCurrentlyCopied ? 'Modify Allocation' : 'Copy Strategy'}
                  </button>
                </div>
              </div>
            );
          })}
        </div>
        )}

      </div>

      {/* MODAL: TRADER DETAILED STATS ANALYSIS */}
      <AnimatePresence>
        {selectedTraderForAnalysis && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
              onClick={() => setSelectedTraderForAnalysis(null)}
            />
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
              className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl w-full max-w-2xl relative z-10 overflow-hidden border border-slate-200 dark:border-slate-800 max-h-[90vh] flex flex-col"
            >
              {/* Header */}
              <div className="p-6 border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <img src={selectedTraderForAnalysis.avatarUrl} alt={selectedTraderForAnalysis.name} className="w-12 h-12 rounded-2xl object-cover border-2 border-brand-red" />
                  <div>
                    <h3 className="text-base font-black text-slate-900 dark:text-white flex items-center gap-2">
                      {selectedTraderForAnalysis.name} <span>{selectedTraderForAnalysis.countryFlag}</span>
                    </h3>
                    <span className="text-xs font-mono text-slate-400">{selectedTraderForAnalysis.handle} — {selectedTraderForAnalysis.badge}</span>
                  </div>
                </div>
                <button onClick={() => setSelectedTraderForAnalysis(null)} className="p-1.5 rounded-lg text-slate-400 hover:text-slate-700 dark:hover:text-white">
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Scrollable Content */}
              <div className="p-6 flex flex-col gap-6 overflow-y-auto">
                {/* Key Numbers Grid */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
                  <div className="p-3 bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
                    <span className="text-[10px] font-black uppercase text-slate-400">Annual Return</span>
                    <div className="text-lg font-black text-emerald-500 font-mono">+{selectedTraderForAnalysis.roiYear}%</div>
                  </div>
                  <div className="p-3 bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
                    <span className="text-[10px] font-black uppercase text-slate-400">Win Rate</span>
                    <div className="text-lg font-black text-slate-900 dark:text-white font-mono">{selectedTraderForAnalysis.winRate}%</div>
                  </div>
                  <div className="p-3 bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
                    <span className="text-[10px] font-black uppercase text-slate-400">Copiers Capital</span>
                    <div className="text-lg font-black text-slate-900 dark:text-white font-mono">{selectedTraderForAnalysis.allocatedCapitalTotal}</div>
                  </div>
                  <div className="p-3 bg-slate-50 dark:bg-slate-800 rounded-xl border border-slate-200 dark:border-slate-700">
                    <span className="text-[10px] font-black uppercase text-slate-400">Max Drawdown</span>
                    <div className="text-lg font-black text-rose-500 font-mono">{selectedTraderForAnalysis.maxDrawdown}%</div>
                  </div>
                </div>

                {/* Strategy Details */}
                <div className="bg-slate-50 dark:bg-slate-950 p-4 rounded-xl border border-slate-200 dark:border-slate-800">
                  <h4 className="text-xs font-black uppercase tracking-wider text-slate-400 mb-1">Strategy Overview</h4>
                  <p className="text-xs font-semibold text-slate-800 dark:text-slate-200 leading-relaxed">
                    {selectedTraderForAnalysis.strategy}
                  </p>
                  <div className="mt-2 text-xs font-mono text-slate-500">
                    Primary Assets: <strong className="text-slate-800 dark:text-slate-200">{selectedTraderForAnalysis.assetFocus}</strong>
                  </div>
                </div>

                {/* Currently Replicated Open Positions */}
                <div>
                  <h4 className="text-xs font-black uppercase tracking-wider text-slate-400 mb-2 flex items-center gap-1.5">
                    <Activity className="w-3.5 h-3.5 text-brand-red" /> Currently Open Positions ({selectedTraderForAnalysis.openPositions.length})
                  </h4>
                  <div className="border border-slate-200 dark:border-slate-800 rounded-xl overflow-hidden">
                    <table className="w-full text-left text-xs font-mono">
                      <thead className="bg-slate-100 dark:bg-slate-800 text-slate-500 uppercase text-[9px] font-black">
                        <tr>
                          <th className="p-2.5">Symbol</th>
                          <th className="p-2.5">Type</th>
                          <th className="p-2.5">Volume</th>
                          <th className="p-2.5">Entry Price</th>
                          <th className="p-2.5 text-right">Floating P&L</th>
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-slate-100 dark:divide-slate-800 text-slate-800 dark:text-slate-200">
                        {selectedTraderForAnalysis.openPositions.map((pos, idx) => (
                          <tr key={idx} className="hover:bg-slate-50/50">
                            <td className="p-2.5 font-bold">{pos.symbol}</td>
                            <td className="p-2.5">
                              <span className={`px-1.5 py-0.5 rounded text-[9px] font-black ${pos.type === 'BUY' ? 'bg-emerald-500/10 text-emerald-500' : 'bg-rose-500/10 text-rose-500'}`}>
                                {pos.type}
                              </span>
                            </td>
                            <td className="p-2.5">{pos.volume} Lots</td>
                            <td className="p-2.5">{pos.entryPrice}</td>
                            <td className={`p-2.5 text-right font-black ${pos.floatingPnL >= 0 ? 'text-emerald-500' : 'text-rose-500'}`}>
                              +${pos.floatingPnL.toFixed(2)}
                            </td>
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>

              {/* Modal Footer */}
              <div className="p-4 border-t border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 flex justify-end gap-3">
                <button
                  onClick={() => setSelectedTraderForAnalysis(null)}
                  className="px-4 py-2.5 text-xs font-bold text-slate-600 dark:text-slate-300 hover:bg-slate-200 dark:hover:bg-slate-800 rounded-xl"
                >
                  Close
                </button>
                <button
                  onClick={() => {
                    setCopyModalTrader(selectedTraderForAnalysis);
                    setSelectedTraderForAnalysis(null);
                  }}
                  className="px-5 py-2.5 bg-brand-red hover:bg-brand-red-hover text-white text-xs font-black rounded-xl shadow-md cursor-pointer"
                >
                  Copy Strategy Now
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* MODAL: COPY TRADER SETUP FORM */}
      <AnimatePresence>
        {copyModalTrader && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
            <motion.div
              initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
              className="absolute inset-0 bg-slate-900/60 backdrop-blur-sm"
              onClick={() => setCopyModalTrader(null)}
            />
            <motion.div
              initial={{ scale: 0.95, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.95, opacity: 0 }}
              className="bg-white dark:bg-slate-900 rounded-2xl shadow-2xl w-full max-w-md relative z-10 overflow-hidden border border-slate-200 dark:border-slate-800"
            >
              <div className="p-5 border-b border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <img src={copyModalTrader.avatarUrl} alt={copyModalTrader.name} className="w-10 h-10 rounded-xl object-cover border border-brand-red" />
                  <div>
                    <h3 className="font-black text-slate-900 dark:text-white text-sm">
                      Copy {copyModalTrader.name}
                    </h3>
                    <span className="text-[10px] text-emerald-500 font-mono font-bold">1Y ROI: +{copyModalTrader.roiYear}%</span>
                  </div>
                </div>
                <button onClick={() => setCopyModalTrader(null)} className="text-slate-400 hover:text-slate-700 dark:hover:text-white">
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="p-6 flex flex-col gap-5">
                {/* Capital Input */}
                <div>
                  <label className="text-xs font-black uppercase tracking-wider text-slate-400 block mb-1.5">
                    Select Capital Allocation (USD)
                  </label>
                  <div className="relative">
                    <span className="absolute left-3.5 top-1/2 -translate-y-1/2 font-mono font-black text-slate-400">$</span>
                    <input
                      type="number"
                      min="100"
                      step="100"
                      value={copyCapitalAmount}
                      onChange={(e) => setCopyCapitalAmount(Math.max(100, Number(e.target.value)))}
                      className="w-full bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 focus:border-brand-red rounded-xl py-3 pl-8 pr-4 text-slate-900 dark:text-white font-mono font-black text-lg focus:outline-none transition"
                    />
                  </div>

                  <div className="flex items-center gap-1.5 mt-2">
                    {[200, 500, 1000, 2500, 5000].map(amt => (
                      <button
                        key={amt}
                        onClick={() => setCopyCapitalAmount(amt)}
                        className={`flex-1 py-1 rounded-md text-[10px] font-mono font-black border transition cursor-pointer ${
                          copyCapitalAmount === amt
                            ? 'bg-brand-red text-white border-brand-red'
                            : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 border-slate-200 dark:border-slate-700'
                        }`}
                      >
                        ${amt >= 1000 ? `${amt / 1000}k` : amt}
                      </button>
                    ))}
                  </div>
                </div>

                {/* Stop Loss Protection slider */}
                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className="text-xs font-black uppercase tracking-wider text-slate-400">
                      Copy Stop-Loss Protection
                    </label>
                    <span className="text-xs font-black font-mono text-brand-red">{copyStopLossPercent}% Limit</span>
                  </div>
                  <input
                    type="range"
                    min="5"
                    max="50"
                    step="5"
                    value={copyStopLossPercent}
                    onChange={(e) => setCopyStopLossPercent(Number(e.target.value))}
                    className="w-full accent-brand-red cursor-pointer"
                  />
                  <p className="text-[10px] text-slate-400 mt-1 font-medium">
                    Automatically stops copying if allocated capital decreases by {copyStopLossPercent}% (${((copyCapitalAmount * copyStopLossPercent) / 100).toFixed(0)} drawdown).
                  </p>
                </div>

                {/* Information Box */}
                <div className="bg-emerald-500/10 border border-emerald-500/20 p-3 rounded-xl text-[11px] text-slate-700 dark:text-slate-300 font-medium">
                  <strong>Instant Replicating:</strong> Replicates current and future orders proportionally based on your ${copyCapitalAmount.toLocaleString()} allocation.
                </div>
              </div>

              <div className="p-4 border-t border-slate-100 dark:border-slate-800 bg-slate-50 dark:bg-slate-950 flex items-center justify-end gap-3">
                <button
                  onClick={() => setCopyModalTrader(null)}
                  className="px-4 py-2 text-xs font-bold text-slate-500 hover:text-slate-800 dark:hover:text-white"
                >
                  Cancel
                </button>
                <button
                  onClick={() => {
                    const trader = copyModalTrader;
                    setCopiedTraderIds(prev => ({
                      ...prev,
                      [trader.id]: { capital: copyCapitalAmount, stopLoss: copyStopLossPercent, date: new Date().toISOString().split('T')[0] }
                    }));
                    setCopyModalTrader(null);
                    if (showToast) showToast(`Successfully started copying ${trader.name} with $${copyCapitalAmount.toLocaleString()} capital!`, 'success');
                  }}
                  className="px-6 py-3 bg-brand-red hover:bg-brand-red-hover text-white font-black text-xs uppercase tracking-wider rounded-xl shadow-md cursor-pointer"
                >
                  Confirm & Start Copying
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* SECTION: PREMIUM ECONOMIC CALENDAR */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 flex flex-col gap-6 shadow-sm relative">
        
        {/* Local calendar toast notification */}
        <AnimatePresence>
          {calendarToast && (
            <motion.div
              initial={{ opacity: 0, y: -20, scale: 0.95 }}
              animate={{ opacity: 1, y: 0, scale: 1 }}
              exit={{ opacity: 0, y: -10, scale: 0.95 }}
              className="absolute top-4 right-6 z-30 bg-slate-900 text-white border border-slate-800 shadow-xl px-4 py-2.5 rounded-xl flex items-center gap-2 text-xs font-bold leading-none"
            >
              <Bell className="w-4 h-4 text-brand-yellow animate-bounce" />
              <span>{calendarToast}</span>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Calendar Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-slate-100 pb-4">
          <div className="flex items-center gap-3 text-left">
            <div className="w-10 h-10 rounded-xl bg-brand-red/10 text-brand-red flex items-center justify-center border border-brand-red/10 shadow-xs">
              <Calendar className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-black text-brand-dark uppercase tracking-wider flex items-center gap-2">
                Axi Live Economic Calendar
              </h3>
              <p className="text-slate-500 text-[11px] font-semibold leading-relaxed">
                Real-time tracking of premium global macroeconomic indices and scheduled central bank announcements.
              </p>
            </div>
          </div>

          {/* Interactive Filters Panel */}
          <div className="flex flex-wrap items-center gap-2.5">
            
            {/* Impact Filter */}
            <div className="flex bg-slate-100/80 p-0.5 rounded-xl border border-slate-200 shadow-xs">
              {['ALL', 'HIGH', 'MEDIUM', 'LOW'].map((lvl) => (
                <button
                  key={lvl}
                  onClick={() => setImpactFilter(lvl as any)}
                  className={`px-3 py-1.5 text-[9px] font-black uppercase rounded-lg tracking-wider transition ${
                    impactFilter === lvl
                      ? 'bg-slate-900 text-white shadow-xs'
                      : 'text-slate-500 hover:text-slate-900'
                  }`}
                >
                  {lvl === 'ALL' ? 'All Impacts' : lvl}
                </button>
              ))}
            </div>

            {/* Currency Filter */}
            <div className="relative">
              <select
                value={currencyFilter}
                onChange={(e) => setCurrencyFilter(e.target.value)}
                className="bg-white border border-slate-200 hover:border-slate-300 focus:border-brand-red text-[11px] font-extrabold text-slate-700 py-1.5 pl-7 pr-4 rounded-xl focus:outline-none transition shadow-xs appearance-none cursor-pointer"
              >
                <option value="ALL">All Currencies</option>
                <option value="USD">USD (US Dollar)</option>
                <option value="EUR">EUR (Euro)</option>
                <option value="GBP">GBP (British Pound)</option>
                <option value="CAD">CAD (Canadian Dollar)</option>
                <option value="AUD">AUD (Australian Dollar)</option>
              </select>
              <Globe className="w-3.5 h-3.5 text-slate-400 absolute left-2.5 top-2.5 pointer-events-none" />
            </div>

          </div>
        </div>

        {/* Events List / Table */}
        <div className="overflow-hidden border border-slate-150 rounded-xl bg-slate-50/50">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs text-slate-600">
              <thead>
                <tr className="bg-slate-100 border-b border-slate-200 text-slate-400 text-[9px] uppercase font-black tracking-wider">
                  <th className="py-2.5 px-4">Scheduled Time</th>
                  <th className="py-2.5 px-3">Currency</th>
                  <th className="py-2.5 px-3">Economic Indicator / Event</th>
                  <th className="py-2.5 px-3 text-center">Relative Impact</th>
                  <th className="py-2.5 px-3 text-right">Forecast</th>
                  <th className="py-2.5 px-3 text-right">Previous</th>
                  <th className="py-2.5 px-4 text-center">Alerts</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-150 bg-white">
                {ECONOMIC_EVENTS.filter(e => {
                  const matchesImpact = impactFilter === 'ALL' || e.impact === impactFilter;
                  const matchesCurrency = currencyFilter === 'ALL' || e.currency === currencyFilter;
                  return matchesImpact && matchesCurrency;
                }).map((e) => {
                  const alertSet = activeAlerts[e.id];
                  return (
                    <tr key={e.id} className="hover:bg-slate-50/60 transition-colors group">
                      {/* Date & Time */}
                      <td className="py-3 px-4 flex flex-col font-bold">
                        <span className="text-slate-800">{e.date}</span>
                        <span className="text-slate-400 text-[10px] flex items-center gap-1 font-semibold mt-0.5">
                          <Clock className="w-3 h-3 text-slate-400 shrink-0" />
                          {e.time}
                        </span>
                      </td>

                      {/* Currency Badge */}
                      <td className="py-3 px-3">
                        <span className="bg-slate-100 border border-slate-200/60 px-2.5 py-1 rounded-md text-[10px] font-mono font-black text-slate-700">
                          {e.currency}
                        </span>
                      </td>

                      {/* Event details */}
                      <td className="py-3 px-3 max-w-[280px]">
                        <div className="flex flex-col">
                          <span className="font-extrabold text-slate-900 leading-tight">
                            {e.eventName}
                          </span>
                          <span className="text-[10px] text-slate-400 font-semibold leading-relaxed mt-0.5 line-clamp-1 group-hover:line-clamp-none transition-all duration-300">
                            {e.desc}
                          </span>
                        </div>
                      </td>

                      {/* Impact badge */}
                      <td className="py-3 px-3 text-center">
                        <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-[9px] font-black uppercase tracking-wider ${
                          e.impact === 'HIGH'
                            ? 'bg-rose-50 border border-rose-200 text-rose-600'
                            : e.impact === 'MEDIUM'
                            ? 'bg-amber-50 border border-amber-250 text-amber-600'
                            : 'bg-slate-100 border border-slate-200 text-slate-500'
                        }`}>
                          <span className={`w-1.5 h-1.5 rounded-full ${
                            e.impact === 'HIGH' ? 'bg-rose-500' : e.impact === 'MEDIUM' ? 'bg-amber-500' : 'bg-slate-400'
                          }`}></span>
                          {e.impact} Impact
                        </span>
                      </td>

                      {/* Forecast value */}
                      <td className="py-3 px-3 text-right font-mono font-bold text-slate-800">
                        {e.forecast}
                      </td>

                      {/* Previous value */}
                      <td className="py-3 px-3 text-right font-mono font-semibold text-slate-400">
                        {e.previous}
                      </td>

                      {/* Notification active alert button */}
                      <td className="py-3 px-4 text-center">
                        <motion.button
                          whileTap={{ scale: 0.9 }}
                          onClick={() => {
                            setActiveAlerts(prev => {
                              const updated = { ...prev, [e.id]: !prev[e.id] };
                              triggerCalendarToast(!prev[e.id] ? `🔔 Alerts slated for ${e.eventName}!` : `🔕 Alerts cleared for ${e.eventName}`);
                              return updated;
                            });
                          }}
                          className={`p-1.5 rounded-lg border transition ${
                            alertSet
                              ? 'bg-brand-red border-brand-red text-white'
                              : 'bg-slate-50 hover:bg-slate-100 border-slate-200 text-slate-400 hover:text-slate-600'
                          }`}
                          title={alertSet ? 'Disable announcement notifications' : 'Schedule live release notification'}
                        >
                          <Bell className="w-3.5 h-3.5 stroke-[2.5]" />
                        </motion.button>
                      </td>
                    </tr>
                  );
                })}

                {ECONOMIC_EVENTS.filter(e => {
                  const matchesImpact = impactFilter === 'ALL' || e.impact === impactFilter;
                  const matchesCurrency = currencyFilter === 'ALL' || e.currency === currencyFilter;
                  return matchesImpact && matchesCurrency;
                }).length === 0 && (
                  <tr>
                    <td colSpan={7} className="py-8 text-center text-slate-400 font-bold uppercase tracking-wider">
                      No matching financial events scheduled for selection filters.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Central Bank Risk Disclosure Footer card */}
        <div className="bg-slate-100/60 border border-slate-200 p-4 rounded-xl text-[10px] text-slate-500 font-semibold text-left leading-relaxed flex items-start gap-2.5">
          <span className="w-5 h-5 shrink-0 bg-brand-red/10 text-brand-red rounded-full flex items-center justify-center font-bold">⚠️</span>
          <p>
            <strong>Macroeconomic Release Advisory:</strong> Spikes in trading activity around high-impact news releases (such as US Non-Farm Payrolls, FOMC Interest Decisions, and core CPI prints) often cause direct liquidity depletion, resulting in sudden widening of ECN bid-ask spreads and severe price slippage. Ensure adequate margin levels before slated releases.
          </p>
        </div>

      </div>

    </div>
  );
}

// Economic Calendar Baseline Data
interface EconomicEvent {
  id: string;
  time: string;
  date: string;
  currency: string;
  eventName: string;
  impact: 'HIGH' | 'MEDIUM' | 'LOW';
  forecast: string;
  previous: string;
  desc: string;
}

const ECONOMIC_EVENTS: EconomicEvent[] = [
  { id: 'ev-1', date: 'Today', time: '08:30 AM', currency: 'USD', eventName: 'Non-Farm Employment Change (NFP)', impact: 'HIGH', forecast: '+185K', previous: '+210K', desc: 'Measures the change in the number of employed people during the previous month, excluding the farming industry.' },
  { id: 'ev-2', date: 'Today', time: '08:30 AM', currency: 'USD', eventName: 'Unemployment Rate', impact: 'HIGH', forecast: '4.0%', previous: '4.1%', desc: 'Measures the percentage of the total workforce that is unemployed and actively seeking employment during the previous month.' },
  { id: 'ev-3', date: 'Tomorrow', time: '05:00 AM', currency: 'EUR', eventName: 'German ZEW Economic Sentiment', impact: 'MEDIUM', forecast: '42.5', previous: '41.3', desc: 'Measures German institutional investor sentiment, reflecting optimism on economic growth projections.' },
  { id: 'ev-4', date: 'Tomorrow', time: '08:30 AM', currency: 'CAD', eventName: 'Core CPI MoM', impact: 'HIGH', forecast: '0.3%', previous: '0.2%', desc: 'Measures the change in the price of goods and services purchased by consumers, excluding volatile food and energy.' },
  { id: 'ev-5', date: 'July 15, 2026', time: '02:00 PM', currency: 'USD', eventName: 'FOMC Interest Rate Decision', impact: 'HIGH', forecast: '5.25%', previous: '5.25%', desc: 'Federal Open Market Committee announcement regarding the short-term interest rate target.' },
  { id: 'ev-6', date: 'July 16, 2026', time: '07:45 AM', currency: 'EUR', eventName: 'ECB Interest Rate Decision', impact: 'HIGH', forecast: '4.00%', previous: '4.25%', desc: 'Governing Council of the ECB decision regarding the main refinancing rate.' },
  { id: 'ev-7', date: 'July 17, 2026', time: '04:30 AM', currency: 'GBP', eventName: 'GDP MoM', impact: 'MEDIUM', forecast: '0.1%', previous: '0.2%', desc: 'Measures the change in the inflation-adjusted value of all goods and services produced by the economy.' },
  { id: 'ev-8', date: 'July 17, 2026', time: '09:30 PM', currency: 'AUD', eventName: 'Retail Sales MoM', impact: 'LOW', forecast: '0.4%', previous: '0.1%', desc: 'Measures the change in the total value of sales at the retail level, a primary gauge of consumer spending.' }
];
